In [610]:
import pandas as pd
import numpy as np
import re
import plotly.graph_objects as go
import plotly.express as px
import os

In [611]:
date="07_01_26.csv"
df=pd.read_csv(fr"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_raw\extarcted_csv\{date}")
print(df.shape)

(30, 27)

In [612]:
df.head(2)

,Kitchen,School,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,Staff_Meals,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,NaN,Kindiga Primary & Junior Secondary School,2026-01-07,Rice and Western.,160,153,134,19,0,2,...,0,NaN,"7 Jan 2026, 12:40:31","7 Jan 2026, 13:20:41",NaN,The food was delicious,Lines were well managed with the help of deputy.,The no of failed taps was 13 higher than yeste...,Actual meals increased to 153 from 145 yesterd...,@James Mbugua SC Kindiga Primary
1,NaN,Githioro Primary School,2026-01-07,White rice and western,280,277,254,23,0,2,...,0,NaN,"7 Jan 2026, 12:35:41","7 Jan 2026, 13:53:47",NaN,Food was appetising,Line management was organised assisted by TOD,Failed taps increased from yesterdayâ€™s 12 to...,Successful taps increased from yesterdayâ€™s 2...,@GITHIORO COMPREHENSIVE

In [613]:
df.isnull().sum()

Kitchen                         30
School                           0
Date                             0
Menu                             0
Projected_Kids                   0
Actual_Meals_Served              0
Successful_Taps                  0
F4E_Supported_Kids               0
Teachers                         0
Staff_Meals                      0
Failed_Taps                      0
New_Registrations                0
New_Tags_Replaced                0
Rice_Remaining                   2
B_W_G_Remaining                  0
Missed_Food                     25
Next_Day_Projection_Students     0
Next_Day_Projection_Teachers     0
Next_Day_Projection_Staff       25
Start_Taping                     0
Stop_Taping                      0
Projection_Comment              25
Comment_1                        0
Comment_2                        0
Comment_3                        0
Comment_4                        0
Reported_By                      0
dtype: int64

In [614]:
#stem and map the school names
df["School"]

0             Kindiga Primary & Junior Secondary School
1                               Githioro Primary School
2                       Kiambururu Comprehensive School
3     Catholic Archdiocese Of Nairobi Gataka Primary...
4                           Kiambururu Secondary School
5                               Mathanja Priamry School
6                                       Githiga Primary
7                                     GATHAITHI PRIMARY
8                                 Gatina Primary School
9                        PCEA Matuguta Secondary School
10                              Gitiha Secondary School
11                                        Ihiga Primary
12                                       Gatitu Primary
13      PCEA Matuguta Primary & Junior Secondary School
14                               Gitombo Primary School
15                                      Githima Primary
16                            Gathangari Primary School
17                                    Kiawairia Primary
18                           Kiawairia Secondary School
19                            Gathiruini Primary School
20                            Kahunira Secondary School
21                        Kahunira Comprehensive School
22              Githunguri Technical & Secondary School
23                               Kiababu Primary School
24                                        Ciiko Primary
25                            Kiawaiguru Primary School
26                           Gathaithi Secondary School
27                    Gikang'a Kageche Secondary School
28                              Mukuyu Secondary School
29                               Kanyore Primary School
Name: School, dtype: object

In [615]:
def clean_school_name(name):
    # Fixing  this typos for mathanja 
    name = name.replace("Primry", "Primary")
    
    # Replacing "Comprehensive" with "Primary"
    name = name.replace("Comprehensive", "Primary")
    
    # chopping the word "School" 
    name = re.sub(r"\b[Ss]chool\b", "", name)
    
    # remaoving  Junior Secondary" or similar suffixes
    name = re.sub(r"& Junior Secondary", "", name, flags=re.IGNORECASE)
    
    # Simplifying Catholic Archdiocese   and pcea
    if "Gataka" in name:
        return "Gataka Primary"
    if "Matuguta" in name:
        if "Secondary" in name:
            return "Matuguta Secondary"
        else:
            return "Matuguta Primary"
    
    #    spacing and capitalization
    name = " ".join(name.split())  # remove extra spaces
    name = name.title()            # standardize case
    
    return name.strip()

In [616]:
df["School"] = df["School"].apply(clean_school_name)

In [617]:
df['School']

0                      Kindiga Primary
1                     Githioro Primary
2                   Kiambururu Primary
3                       Gataka Primary
4                 Kiambururu Secondary
5                     Mathanja Priamry
6                      Githiga Primary
7                    Gathaithi Primary
8                       Gatina Primary
9                   Matuguta Secondary
10                    Gitiha Secondary
11                       Ihiga Primary
12                      Gatitu Primary
13                    Matuguta Primary
14                     Gitombo Primary
15                     Githima Primary
16                  Gathangari Primary
17                   Kiawairia Primary
18                 Kiawairia Secondary
19                  Gathiruini Primary
20                  Kahunira Secondary
21                    Kahunira Primary
22    Githunguri Technical & Secondary
23                     Kiababu Primary
24                       Ciiko Primary
25                  Kiawaiguru Primary
26                 Gathaithi Secondary
27          Gikang'A Kageche Secondary
28                    Mukuyu Secondary
29                     Kanyore Primary
Name: School, dtype: object

In [618]:

# creating a new columns of  the kichen served for each school 

kiambu_kitchen_schools=["Githunguri Technical & Secondary", "Kahunira Primary", "Ciiko Primary", "Kahunira Secondary", "Kiababu Primary"]
def map_kitchen_served(school_name):
    if school_name in kiambu_kitchen_schools:
        return 'kiambu kitchen'
    else:
        return 'Githunguri'
df["Kitchen"] = df["School"].apply(map_kitchen_served)

In [619]:
df.head()

,Kitchen,School,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,Staff_Meals,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,Githunguri,Kindiga Primary,2026-01-07,Rice and Western.,160,153,134,19,0,2,...,0,NaN,"7 Jan 2026, 12:40:31","7 Jan 2026, 13:20:41",NaN,The food was delicious,Lines were well managed with the help of deputy.,The no of failed taps was 13 higher than yeste...,Actual meals increased to 153 from 145 yesterd...,@James Mbugua SC Kindiga Primary
1,Githunguri,Githioro Primary,2026-01-07,White rice and western,280,277,254,23,0,2,...,0,NaN,"7 Jan 2026, 12:35:41","7 Jan 2026, 13:53:47",NaN,Food was appetising,Line management was organised assisted by TOD,Failed taps increased from yesterdayâ€™s 12 to...,Successful taps increased from yesterdayâ€™s 2...,@GITHIORO COMPREHENSIVE
2,Githunguri,Kiambururu Primary,2026-01-07,White Rice and Western,250,244,216,28,0,3,...,0,NaN,"7 Jan 2026, 12:25:58","7 Jan 2026, 13:30:04",NaN,The food was hot and delicious,Line management was smooth and fast,Failed taps decreased from 8 to 5.We still had...,Actual meals served increased from 225 to 244....,@Kiambururu Comprehensive School
3,Githunguri,Gataka Primary,2026-01-07,Rice and Western,260,245,222,23,1,2,...,2,NaN,"7 Jan 2026, 12:42:26","7 Jan 2026, 13:40:54",NaN,The food was delicious,The queue was well managed by the school coord...,"The number of failed taps rose from 20 to 21, ...",The number of actual meals rose from 221 to 24...,@Catholic archdiocese of Nairobi Gataka primar...
4,Githunguri,Kiambururu Secondary,2026-01-07,White rice with western,100,133,133,0,0,3,...,0,NaN,"7 Jan 2026, 13:40:54","7 Jan 2026, 14:43:02",NaN,The food was delicious students enjoyed the meal,line management was smooth,failed taps today was 3 been the first day of ...,successful taps was 133 been the day of openin...,@Salome-kiambururu secondary school

In [620]:
#schools type 
def get_school_type(name):
    name = name.lower()
    if "secondary" in name:
        return "Secondary"
    else:
        return "Primary"

df["School_Type"] = df["School"].apply(get_school_type)

#for good visual  i rearrabge the columns so school type can be be next to school name
cols = list(df.columns)
cols.insert(2, cols.pop(cols.index("School_Type")))
df = df[cols]

In [621]:
df.head(30)

,Kitchen,School,School_Type,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,Githunguri,Kindiga Primary,Primary,2026-01-07,Rice and Western.,160,153,134,19,0,...,0,NaN,"7 Jan 2026, 12:40:31","7 Jan 2026, 13:20:41",NaN,The food was delicious,Lines were well managed with the help of deputy.,The no of failed taps was 13 higher than yeste...,Actual meals increased to 153 from 145 yesterd...,@James Mbugua SC Kindiga Primary
1,Githunguri,Githioro Primary,Primary,2026-01-07,White rice and western,280,277,254,23,0,...,0,NaN,"7 Jan 2026, 12:35:41","7 Jan 2026, 13:53:47",NaN,Food was appetising,Line management was organised assisted by TOD,Failed taps increased from yesterdayâ€™s 12 to...,Successful taps increased from yesterdayâ€™s 2...,@GITHIORO COMPREHENSIVE
2,Githunguri,Kiambururu Primary,Primary,2026-01-07,White Rice and Western,250,244,216,28,0,...,0,NaN,"7 Jan 2026, 12:25:58","7 Jan 2026, 13:30:04",NaN,The food was hot and delicious,Line management was smooth and fast,Failed taps decreased from 8 to 5.We still had...,Actual meals served increased from 225 to 244....,@Kiambururu Comprehensive School
3,Githunguri,Gataka Primary,Primary,2026-01-07,Rice and Western,260,245,222,23,1,...,2,NaN,"7 Jan 2026, 12:42:26","7 Jan 2026, 13:40:54",NaN,The food was delicious,The queue was well managed by the school coord...,"The number of failed taps rose from 20 to 21, ...",The number of actual meals rose from 221 to 24...,@Catholic archdiocese of Nairobi Gataka primar...
4,Githunguri,Kiambururu Secondary,Secondary,2026-01-07,White rice with western,100,133,133,0,0,...,0,NaN,"7 Jan 2026, 13:40:54","7 Jan 2026, 14:43:02",NaN,The food was delicious students enjoyed the meal,line management was smooth,failed taps today was 3 been the first day of ...,successful taps was 133 been the day of openin...,@Salome-kiambururu secondary school
5,Githunguri,Mathanja Priamry,Primary,2026-01-07,rice and western,200,162,143,19,0,...,0,NaN,"7 Jan 2026, 12:30:13","7 Jan 2026, 13:30:22",NaN,food was delicious,I managed the queue without any assistance,today we had 3 failed taps an increase compare...,today we had 162 actual meals served an increa...,@mathanja primary school
6,Githunguri,Githiga Primary,Primary,2026-01-07,White rice and Western,330,318,287,31,0,...,0,NaN,"7 Jan 2026, 12:30:51","7 Jan 2026, 13:30:55",NaN,Food was sweet and delicious,Lines Management was smooth,Failed taps increased from21 to 22.Parents fo...,Actual meals increased from 286 to 318.turn o...,@Nicholas-SC - Githiga Comprehensive
7,Githunguri,Gathaithi Primary,Primary,2026-01-07,White rice and western,400,403,370,33,0,...,5,NaN,"7 Jan 2026, 12:40:56","7 Jan 2026, 13:50:01",NaN,food was good,TOD assisted with queue management,We had 50 failed taps a rise from 21. Some par...,Successful taps increased from 351 to 403,@P.C.E.A Gathaithi primary and Junior secondar...
8,Githunguri,Gatina Primary,Primary,2026-01-07,white rice and Western,400,391,339,52,0,...,0,NaN,"7 Jan 2026, 12:31:02","7 Jan 2026, 15:30:13",NaN,food was delicious,line was smooth and orderly,failed taps were 12 a decrease from yesterday'...,Actual meals served were 391 an increase from ...,@Kang'ethe Dennis
9,Githunguri,Matuguta Secondary,Secondary,2026-01-07,White Rice & Western,80,82,82,0,0,...,0,NaN,"7 Jan 2026, 12:50:00","7 Jan 2026, 13:10:24",NaN,Food was hot and delicious,Queues were orderly and well managed by the he...,Number of failed taps today increased from 03 ...,Successful taps today were 82 higher in compar...,@Njeri -Matuguta secondary school
10,Githunguri,Gitiha Secondary,Secondary,2026-01-07,White rice and western stew,80,75,75,0,0,...,0,NaN,"7 Jan 2026, 12:39:02","7 Jan 2026, 13:11:38",NaN,Food was hot and of desired temperatures,The queue was manageable by help from the teac...,"There was no failed taps, improvement noted",The number had decreased since students were s...,@Hannah Mbugua
11,Githunguri,Ihiga Primary,Primary,2026-01-07,Rice and Western,160,153,140,12,0,...,0,NaN,"7 Jan 2026, 12:40:45","7 Jan 2026, 13:20:55",NaN,Food was Delicious,Queues were manageable,Today's failed taps was 0 a decrease from yest...,Successful taps was 153 the same as yesterday'...,@Naomi SC-Ihiga Comprehensive
12,Githunguri,Gatitu Primary,Primary,2026-01-07,RICE AND WESTERN.,350,316,291,25,1,...,1,NaN,"7 Jan 2026, 12:00:49","7 Jan 2026, 13:50:56",NaN,Food was well cooked and enough for all.,Lines moved from class to class under ToD's co...,An increase from 7 to 12 today which was highl...,Successful taps also decreased from 296 to 291...,@Wambui ikonya -sc- Gatitu comprehensive
13,Githunguri,Matuguta Primary,Primary,2026-01-07,Rice and western,440,428,398,30,2,...,2,NaN,"7 Jan 2026, 12:40:06","7 Jan 2026, 13:40:12",NaN,Food was delicious,Queue was well managed,Failed taps were 13 an increase of 4 taps from...,Actual meals were 428 an increase of 21 taps ...,@Matuguta primary
14,Githunguri,Gitombo Primary,Primary,2026-01-07,White rice and Western,180,168,156,12,0,...,0,NaN,"7 Jan 2026, 12:30:02","7 Jan 2026, 13:30:16",NaN,Food was delicious students enjoyed,Queue was manageable,Today failed tap was 5 an increase of 3 from 2...,Actual meals served today was 168 an increase ...,@Veronica Mwaura -S/C- Gitombo primary
15,Githunguri,Githima Primary,Primary,2026-01-07,white rice and western,210,196,172,24,0,...,4,NaN,"7 Jan 2026, 12:40:17","7 Jan 2026, 13:40:24",NaN,The food was delicious,I managed the queue and the kids were discipli...,We had 6 failed taps which is an increase from...,We had 196 actual meals served which is an inc...,@Brenda kamawe Githima primary and junior seco...
16,Githunguri,Gathangari Primary,Primary,2026-01-07,Rice and western,380,306,271,25,0,...,0,NaN,"7 Jan 2026, 12:50:23","7 Jan 2026, 14:00:36",NaN,Food was delicious,Queue was smoothly managed by the teacher,Failed taps increased from 19to 55.Parents did...,I successful taps decreased from 331 to 306.so...,@Pauline Gatimu
17,Githunguri,Kiawairia Primary,Primary,2026-01-07,Rice and western,130,125,110,15,2,...,2,NaN,"7 Jan 2026, 12:00:53","7 Jan 2026, 13:30:21",NaN,Food was delicious,Lines were neat and ordely,We had 4 failed taps same as yesterday some pa...,We had 110 successful taps an increase from y...,@Mary kimani SC kiawairia comprehensive school
18,Githunguri,Kiawairia Secondary,Secondary,2026-01-07,White rice and western,50,41,41,0,0,...,0,NaN,"7 Jan 2026, 12:05:44","7 Jan 2026, 12:20:51",NaN,Food was delicious and appetizing,Line management was transitioning good assiste...,failed taps were 2 being on an opening day,Actual meals were 41 bring on an opening day,@Patrick Kariuki Kiawaria secondary school Tapper
19,Githunguri,Gathiruini Primary,Primary,2026-01-07,Rice and western,240,199,179,20,0,...,0,NaN,"7 Jan 2026, 12:30:55","7 Jan 2026, 13:30:07",NaN,Lunch was delicious,Line management was good with help of teacher ...,Failed taps today were 25 an increase 7 this i...,Actual meal today were 199 a decrease from 225...,@Catherine Wanjiru
20,kiambu kitchen,Kahunira Secondary,Secondary,2026-01-07,Pilau rice & western ndengu,150,98,98,0,0,...,0,3.0,"7 Jan 2026, 13:10:44","7 Jan 2026, 13:50:35",Expecting students will continue,Food was tasty,Queue was well managed by TOD,"Failed taps increased from 3 to 19, respective...",Actual meals served today decreased from 103 t...,@ANTHONY
21,kiambu kitchen,Kahunira Primary,Primary,2026-01-07,Pilau Rice & Western Ndengu,600,611,558,53,0,...,0,4.0,"7 Jan 2026, 12:40:48","7 Jan 2026, 13:45:57",We are expecting a slight increase tomorrow as...,Food was delicious and at good temperatures.,Queue management was well executed by TOD,"Failed taps increased from 19 to 31, respectiv...",Actual meals served today increased from513 to...,@Mwangi Mary Kahunira Comprehensive
22,kiambu kitchen,Githunguri Technical & Secondary,Secondary,2026-01-07,Rice& western stew,140,109,109,0,0,...,0,2.0,"7 Jan 2026, 13:30:59","7 Jan 2026, 13:58:22",More students expected as most will have,Meals were hot and delicious,Queue was manageable and fast moving,More students compared to yesterday,Students who hadn't paid for their meals had d...,@Mercy Njeri Nyambura
23,kiambu kitchen,Kiababu Primary,Primary,2026-01-07,Masala rice and western,250,250,224,26,0,...,0,2.0,"7 Jan 2026, 12:40:47","7 Jan 2026, 13:20:53",Expecting more kids to,The food was delicious,Queue was neat with the help of the teacher on...,Failed taps decreased from 13 to 9 as most par...,Successful taps increased from 230 to 250 as m...,@kiaibabu primary school
24,kiambu kitchen,Ciiko Primary,Primary,2026-01-07,Masala rice and western,700,646,608,38,0,...,0,5.0,"7 Jan 2026, 13:00:04","7 Jan 2026, 14:00:57",Tomorrow we expected about 100 news comer will...,The food was hot and delicious,The queue was managed by teacher on duty,Failed taps increased from 8 to 17,Increased from 433 to 646,@Ciiko Comprehensive school -SL- Samy Migwi
25,Githunguri,Kiawaiguru Primary,Primary,2026-01-07,Rice and Western,210,186,169,17,2,...,2,NaN,"7 Jan 2026, 12:30:00","7 Jan 2026, 13:30:00",NaN,Lunch was delicious.,Line was oderly.,Failed taps decreased from yesterday’s 7 to to...,Actual meals served increased from yesterday’s...,@KIAWAIGURU PRIMARY SCHOOL
26,Githunguri,Gathaithi Secondary,Secondary,2026-01-07,Rice and western,90,90,90,0,0,...,0,NaN,"7 Jan 2026, 13:20:47","7 Jan 2026, 14:14:12",NaN,Food was delicious,The queue was managed,Failed taps increased as many parents didn't t...,Successful taps were more than yesterday,@Joseph mburu nga'ang'a
27,Githunguri,Gikang'A Kageche Secondary,Secondary,2026-01-07,White Rice and Western,180,77,77,0,0,...,0,NaN,"7 Jan 2026, 13:15:29","7 Jan 2026, 13:35:40",NaN,Food was delicious,Queue was well managed by the TOD,Today's failed taps decreased from 7 to 4.,Today's successful taps decreased from 147 to ...,@Pauline Gatimu
28,Githunguri,Mukuyu Secondary,Secondary,2026-01-07,Rice and western,200,187,187,0,0,...,0,NaN,"7 Jan 2026, 12:40:18","7 Jan 2026, 13:22:29",NaN,Food was delicious,Queue managed was good,Today failed taps were five because some paren...,Today's actual tap was 187 and it was opening day,@Kanyore Comprehensive School
29,Githunguri,Kanyore Primary,Primary,2026-01-07,Rice and Western,530,505,473,32,0,...,0,NaN,"7 Jan 2026, 12:40:00","7 Jan 2026, 13:53:00",NaN,Food was delicious,Queue was well managed,Today’s failed taps were 48 which is more than...,The number of actual taps were 505 which is mo...,@Kanyore Comprehensive School

In [622]:
df.head(2)

,Kitchen,School,School_Type,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,Githunguri,Kindiga Primary,Primary,2026-01-07,Rice and Western.,160,153,134,19,0,...,0,NaN,"7 Jan 2026, 12:40:31","7 Jan 2026, 13:20:41",NaN,The food was delicious,Lines were well managed with the help of deputy.,The no of failed taps was 13 higher than yeste...,Actual meals increased to 153 from 145 yesterd...,@James Mbugua SC Kindiga Primary
1,Githunguri,Githioro Primary,Primary,2026-01-07,White rice and western,280,277,254,23,0,...,0,NaN,"7 Jan 2026, 12:35:41","7 Jan 2026, 13:53:47",NaN,Food was appetising,Line management was organised assisted by TOD,Failed taps increased from yesterdayâ€™s 12 to...,Successful taps increased from yesterdayâ€™s 2...,@GITHIORO COMPREHENSIVE

In [623]:
def get_rice_variant(menu_item):
    if pd.isna(menu_item):
        return ""
    menu_item = menu_item.lower()
    if "masala" in menu_item:
        return "Masala"
    elif "tumeric" in menu_item:
        return "Tumeric"
    else:
        return "White"

df["Rice_variant"] = df["Menu"].apply(get_rice_variant)
# For column reordering to be next to menu 
cols = list(df.columns)
cols.insert(5, cols.pop(cols.index("Rice_variant")))
df = df[cols]

In [624]:
def clean_menu(name):
    if pd.isna(name):
        return None
    
    # Normalize casing and whitespace
    name = name.strip().title()
    
    # Replace connectors
    name = name.replace("&", "And")
    
    # Standardize synonyms/abbreviations
    name = re.sub(r"\bGg\b", "Greengrams", name, flags=re.IGNORECASE)
    name = name.replace("Green Gram", "Greengrams")
    name = name.replace("Green Grams", "Greengrams")
    
    # If "Rice" exists, discard everything before it
    if "Rice" in name:
        idx = name.find("Rice")
        name = name[idx:]
    
    # Canonical mapping
    if "Greengrams" in name:
        return "Rice and Greengrams"
    elif "Beans" in name:
        return "Rice and Beans"
    elif "Western" in name:
        return "Rice and Western"
    
    # If no keyword matched, return substring after Rice
    return name

In [625]:
df["Menu"] = df["Menu"].apply(clean_menu)

In [626]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Kitchen                       30 non-null     object
 1   School                        30 non-null     object
 2   School_Type                   30 non-null     object
 3   Date                          30 non-null     object
 4   Menu                          30 non-null     object
 5   Rice_variant                  30 non-null     object
 6   Projected_Kids                30 non-null     int64
 7   Actual_Meals_Served           30 non-null     int64
 8   Successful_Taps               30 non-null     int64
 9   F4E_Supported_Kids            30 non-null     int64
 10  Teachers                      30 non-null     int64
 11  Staff_Meals                   30 non-null     int64
 12  Failed_Taps                   30 non-null     int64
 13  New_Registrations             30 non-null     int64
 14  New_Tags_Replaced             30 non-null     int64
 15  Rice_Remaining                28 non-null     float64
 16  B_W_G_Remaining               30 non-null     float64
 17  Missed_Food                   5 non-null      float64
 18  Next_Day_Projection_Students  30 non-null     int64
 19  Next_Day_Projection_Teachers  30 non-null     int64
 20  Next_Day_Projection_Staff     5 non-null      float64
 21  Start_Taping                  30 non-null     object
 22  Stop_Taping                   30 non-null     object
 23  Projection_Comment            5 non-null      object
 24  Comment_1                     30 non-null     object
 25  Comment_2                     30 non-null     object
 26  Comment_3                     30 non-null     object
 27  Comment_4                     30 non-null     object
 28  Reported_By                   30 non-null     object
dtypes: float64(4), int64(11), object(14)
memory usage: 6.9+ KB

In [627]:
# Convert to datetime
df["Start_Taping"] = pd.to_datetime(df["Start_Taping"], format="%d %b %Y, %H:%M:%S")
df["Stop_Taping"] = pd.to_datetime(df["Stop_Taping"], format="%d %b %Y, %H:%M:%S")
# Compute duration
lunch_time= df["Stop_Taping"] - df["Start_Taping"]
df["Lunch_Time_Min"] = (lunch_time.dt.total_seconds() / 60).round(0).astype('Int64')  # Convert to minutes and round


cols = list(df.columns)
# moving Lunch_Time_Min to index 23 nest to the parent columns
cols.insert(23, cols.pop(cols.index("Lunch_Time_Min")))

# Reassign DataFrame with new order
df = df[cols]

In [628]:

pd.set_option("display.max_rows", None)
df.head(3)

,Kitchen,School,School_Type,Date,Menu,Rice_variant,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,...,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Lunch_Time_Min,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,Githunguri,Kindiga Primary,Primary,2026-01-07,Rice and Western,White,160,153,134,19,...,NaN,2026-01-07 12:40:31,2026-01-07 13:20:41,40,NaN,The food was delicious,Lines were well managed with the help of deputy.,The no of failed taps was 13 higher than yeste...,Actual meals increased to 153 from 145 yesterd...,@James Mbugua SC Kindiga Primary
1,Githunguri,Githioro Primary,Primary,2026-01-07,Rice and Western,White,280,277,254,23,...,NaN,2026-01-07 12:35:41,2026-01-07 13:53:47,78,NaN,Food was appetising,Line management was organised assisted by TOD,Failed taps increased from yesterdayâ€™s 12 to...,Successful taps increased from yesterdayâ€™s 2...,@GITHIORO COMPREHENSIVE
2,Githunguri,Kiambururu Primary,Primary,2026-01-07,Rice and Western,White,250,244,216,28,...,NaN,2026-01-07 12:25:58,2026-01-07 13:30:04,64,NaN,The food was hot and delicious,Line management was smooth and fast,Failed taps decreased from 8 to 5.We still had...,Actual meals served increased from 225 to 244....,@Kiambururu Comprehensive School

In [629]:
df.head(10)

,Kitchen,School,School_Type,Date,Menu,Rice_variant,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,...,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Lunch_Time_Min,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,Githunguri,Kindiga Primary,Primary,2026-01-07,Rice and Western,White,160,153,134,19,...,NaN,2026-01-07 12:40:31,2026-01-07 13:20:41,40,NaN,The food was delicious,Lines were well managed with the help of deputy.,The no of failed taps was 13 higher than yeste...,Actual meals increased to 153 from 145 yesterd...,@James Mbugua SC Kindiga Primary
1,Githunguri,Githioro Primary,Primary,2026-01-07,Rice and Western,White,280,277,254,23,...,NaN,2026-01-07 12:35:41,2026-01-07 13:53:47,78,NaN,Food was appetising,Line management was organised assisted by TOD,Failed taps increased from yesterdayâ€™s 12 to...,Successful taps increased from yesterdayâ€™s 2...,@GITHIORO COMPREHENSIVE
2,Githunguri,Kiambururu Primary,Primary,2026-01-07,Rice and Western,White,250,244,216,28,...,NaN,2026-01-07 12:25:58,2026-01-07 13:30:04,64,NaN,The food was hot and delicious,Line management was smooth and fast,Failed taps decreased from 8 to 5.We still had...,Actual meals served increased from 225 to 244....,@Kiambururu Comprehensive School
3,Githunguri,Gataka Primary,Primary,2026-01-07,Rice and Western,White,260,245,222,23,...,NaN,2026-01-07 12:42:26,2026-01-07 13:40:54,58,NaN,The food was delicious,The queue was well managed by the school coord...,"The number of failed taps rose from 20 to 21, ...",The number of actual meals rose from 221 to 24...,@Catholic archdiocese of Nairobi Gataka primar...
4,Githunguri,Kiambururu Secondary,Secondary,2026-01-07,Rice and Western,White,100,133,133,0,...,NaN,2026-01-07 13:40:54,2026-01-07 14:43:02,62,NaN,The food was delicious students enjoyed the meal,line management was smooth,failed taps today was 3 been the first day of ...,successful taps was 133 been the day of openin...,@Salome-kiambururu secondary school
5,Githunguri,Mathanja Priamry,Primary,2026-01-07,Rice and Western,White,200,162,143,19,...,NaN,2026-01-07 12:30:13,2026-01-07 13:30:22,60,NaN,food was delicious,I managed the queue without any assistance,today we had 3 failed taps an increase compare...,today we had 162 actual meals served an increa...,@mathanja primary school
6,Githunguri,Githiga Primary,Primary,2026-01-07,Rice and Western,White,330,318,287,31,...,NaN,2026-01-07 12:30:51,2026-01-07 13:30:55,60,NaN,Food was sweet and delicious,Lines Management was smooth,Failed taps increased from21 to 22.Parents fo...,Actual meals increased from 286 to 318.turn o...,@Nicholas-SC - Githiga Comprehensive
7,Githunguri,Gathaithi Primary,Primary,2026-01-07,Rice and Western,White,400,403,370,33,...,NaN,2026-01-07 12:40:56,2026-01-07 13:50:01,69,NaN,food was good,TOD assisted with queue management,We had 50 failed taps a rise from 21. Some par...,Successful taps increased from 351 to 403,@P.C.E.A Gathaithi primary and Junior secondar...
8,Githunguri,Gatina Primary,Primary,2026-01-07,Rice and Western,White,400,391,339,52,...,NaN,2026-01-07 12:31:02,2026-01-07 15:30:13,179,NaN,food was delicious,line was smooth and orderly,failed taps were 12 a decrease from yesterday'...,Actual meals served were 391 an increase from ...,@Kang'ethe Dennis
9,Githunguri,Matuguta Secondary,Secondary,2026-01-07,Rice and Western,White,80,82,82,0,...,NaN,2026-01-07 12:50:00,2026-01-07 13:10:24,20,NaN,Food was hot and delicious,Queues were orderly and well managed by the he...,Number of failed taps today increased from 03 ...,Successful taps today were 82 higher in compar...,@Njeri -Matuguta secondary school

In [630]:
df.nunique()

Kitchen                          2
School                          30
School_Type                      2
Date                             1
Menu                             1
Rice_variant                     2
Projected_Kids                  23
Actual_Meals_Served             29
Successful_Taps                 30
F4E_Supported_Kids              18
Teachers                         3
Staff_Meals                      6
Failed_Taps                     19
New_Registrations               11
New_Tags_Replaced               11
Rice_Remaining                  12
B_W_G_Remaining                 13
Missed_Food                      1
Next_Day_Projection_Students    24
Next_Day_Projection_Teachers     5
Next_Day_Projection_Staff        4
Start_Taping                    30
Stop_Taping                     30
Lunch_Time_Min                  21
Projection_Comment               5
Comment_1                       19
Comment_2                       29
Comment_3                       30
Comment_4                       30
Reported_By                     28
dtype: int64

In [631]:
#lets use os 
output_dir = r"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed"
base = date.replace(".csv", "")
output_path = os.path.join(output_dir, f"{base}_clean.csv")
df.to_csv(output_path, index=False)
print("Saved:", output_path)

Saved: C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed\07_01_26_clean.csv