In [1]:
import pandas as pd
import numpy as np
import re
import plotly.graph_objects as go
import plotly.express as px
import os

In [2]:
date="05_01_2026.csv"
df=pd.read_csv(fr"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_raw\extarcted_csv\{date}")
print(df.shape)

(59, 27)

In [3]:
df.head()

,Kitchen,School,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,Staff_Meals,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,NaN,Gathangari Primary School,2026-01-05,Rice and GG,220,219,200,19.0,0,3,...,0.0,NaN,"5 Jan 2026, 12:40:55","5 Jan 2026, 13:30:06",NaN,Food was delicious and hot,Queue was smoothly managed by the T.O.D,Being the first day in school it was 17,Successful taps was 219.Kids did not report we...,@Pauline Gatimu
1,NaN,Kigumo Primary,2026-01-05,White Rice and GreenGrams,110,125,106,19.0,0,2,...,0.0,NaN,"5 Jan 2026, 12:40:35","5 Jan 2026, 13:20:40",NaN,Food was delicious,Line management was orderly assisted by the te...,We had 14 failed taps parents forgot to top up,"We had 125 actual meals served,most kids were ...",@S C PCEA Kigumo Comprehensive School
2,NaN,Kihuririo Primary School,2026-01-05,Rice and Gg,330,301,254,47.0,0,3,...,0.0,NaN,"5 Jan 2026, 12:50:43","5 Jan 2026, 14:00:49",NaN,The food was delicious,Line management was okay,Failed taps were 15,Successful taps were 254,@kihuririo primary
3,NaN,Gitombo Primary School,2026-01-05,White rice and Green grams,90,126,111,15.0,0,2,...,0.0,NaN,"5 Jan 2026, 12:50:36","5 Jan 2026, 13:23:43",NaN,Food was delicious.,Queue was manageable.,Failed taps were 8 some parents forgot to top ...,Actual meal served today was 126 most kids rep...,@Veronica Mwaura -S/C- Gitombo primary
4,NaN,Kiambururu Comprehensive School,2026-01-05,White Rice and GG,180,167,148,19.0,0,3,...,0.0,NaN,"5 Jan 2026, 12:50:40","5 Jan 2026, 13:57:50",NaN,Food was delicious,Line management was smooth,Failed taps were 9.Some parents hadn't topped ...,Actual meals served was 167.This is because th...,@Kiambururu Comprehensive School

In [101]:
df.isnull().sum()

Kitchen                         30
School                           0
Date                             0
Menu                             0
Projected_Kids                   0
Actual_Meals_Served              0
Successful_Taps                  0
F4E_Supported_Kids               0
Teachers                         0
Staff_Meals                      0
Failed_Taps                      0
New_Registrations                0
New_Tags_Replaced                0
Rice_Remaining                   0
B_W_G_Remaining                  0
Missed_Food                     25
Next_Day_Projection_Students     0
Next_Day_Projection_Teachers     0
Next_Day_Projection_Staff       25
Start_Taping                     0
Stop_Taping                      0
Projection_Comment              25
Comment_1                        0
Comment_2                        0
Comment_3                        0
Comment_4                        0
Reported_By                      0
dtype: int64

In [4]:
#stem and map the school names
df["School"]

0                             Gathangari Primary School
1                                        Kigumo Primary
2                              Kihuririo Primary School
3                                Gitombo Primary School
4                       Kiambururu Comprehensive School
5                              Giathieko Primary School
6                                         Ihiga Primary
7                                        Gatitu Primary
8                                  Ngewa Primary School
9                                        Kanjai Primary
10                                      Githiga Primary
11                              Githioro Primary School
12                              Mathanja Priamry School
13      PCEA Matuguta Primary & Junior Secondary School
14                            Kiawaiguru Primary School
15    Catholic Archdiocese Of Nairobi Gataka Primary...
16                                      Githima Primary
17                            Gathiruini Primary School
18                                        Miiri Primary
19    Ceb Riamute Nursery, Primary & Junior Secondar...
20                                Thuita Primary School
21                              Komothai Primary School
22                              Mitahato Primary School
23            Kindiga Primary & Junior Secondary School
24                                    GATHAITHI PRIMARY
25                                Gatina Primary School
26                               Kanyore Primary School
27                                Kambui Primary School
28                               Gathugu Primary School
29                                Miguta Primary School
30                                        Ikinu Primary
31                                 Nyaga Primary School
32                                    Kiawairia Primary
33                               Ndireti Primary School
34                                 Njunu Primary School
35                              Kibichoi Primary School
36                                Loreto Primary School
37                           Lioki Comprehensive School
38                          Mayuyu Comprehensive School
39                      PCEA Karia Comprehensive School
40                        Muchatha Comprehensive School
41                         Kawaida Comprehensive School
42                          Karuri Comprehensive School
43                    Kamondo Primary and Junior School
44                     Ngemwa Primary and Junior School
45                                 Riara Primary School
46                        Gathanji Comprehensive School
47                      Mungai Chengecha Primary School
48                         Kiambaa Comprehensive School
49                         Kibathi Comprehensive School
50                               Kiababu Primary School
51                 PCEA Githunguri Comprehensive School
52                        Kahunira Comprehensive School
53                         Kiairia Comprehensive School
54                       Muongoiya Comprehensive School
55                          Chief Wandie Primary School
56                       AK Magugu Comprehensive School
57                   Njenga Karume Comprehensive School
58                                        Ciiko Primary
Name: School, dtype: object

In [5]:
def clean_school_name(name):
    # Fixing  this typos for mathanja 
    name = name.replace("Primry", "Primary")
    
    # Replacing "Comprehensive" with "Primary"
    name = name.replace("Comprehensive", "Primary")
    
    # chopping the word "School" 
    name = re.sub(r"\b[Ss]chool\b", "", name)
    
    # remaoving  Junior Secondary" or similar suffixes
    name = re.sub(r"& Junior Secondary", "", name, flags=re.IGNORECASE)
    
    
    # Simplifying Catholic Archdiocese   and pcea
    if "Gataka" in name:
        return "Gataka Primary"
    if "Mitahato" in name:
        if "Secondary" in name:
            return "Mitahato Secondary"
        else:
            return "Mitahato Primary"
    if "Matuguta" in name:
        if "Secondary" in name:
            return "Matuguta Secondary"
        else:
            return "Matuguta Primary"
    if "Riamute" in name:
        return "Riamute Primary"
    if "Ngemwa" in name:
        if "Secondary" in name:
            return "Ngemwa Secondary"
        else:
            return "Ngemwa Primary"
    if "Lioki" in name:
        if "Secondary" in name:
            return "Lioki Secondary"
        else:
            return "Lioki Primary"
    if "Karia" in name:
        if "Secondary" in name:
            return "Karia Secondary"
        else:
            return "Karia Primary"
    if "Kamondo" in name:
        if "Secondary" in name:
            return "Kamondo Secondary"
        else:
            return "Kamondo Primary"
    if "Githunguri" in name:
        if "Secondary" in name:
            return "Githunguri Tech Secondary"
        else:
            return "Githunguri Primary"
    if "Mathanja" in name:
        return "Mathanja Primary"
    if "Kagema" in name:
        if "Secondary" in name:
            return "Kagema Secondary"
        else:
            return "Kagema Primary"
    
    
    
    #    spacing and capitalization
    name = " ".join(name.split())  # remove extra spaces
    name = name.title()            # standardize case
    
    return name.strip()

In [6]:
df["School"] = df["School"].apply(clean_school_name)

In [7]:
pd.describe_option("display.max_rows")
pd.set_option("display.max_rows", 100)

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]

In [8]:
df['School']

0           Gathangari Primary
1               Kigumo Primary
2            Kihuririo Primary
3              Gitombo Primary
4           Kiambururu Primary
5            Giathieko Primary
6                Ihiga Primary
7               Gatitu Primary
8                Ngewa Primary
9               Kanjai Primary
10             Githiga Primary
11            Githioro Primary
12            Mathanja Primary
13            Matuguta Primary
14          Kiawaiguru Primary
15              Gataka Primary
16             Githima Primary
17          Gathiruini Primary
18               Miiri Primary
19             Riamute Primary
20              Thuita Primary
21            Komothai Primary
22            Mitahato Primary
23             Kindiga Primary
24           Gathaithi Primary
25              Gatina Primary
26             Kanyore Primary
27              Kambui Primary
28             Gathugu Primary
29              Miguta Primary
30               Ikinu Primary
31               Nyaga Primary
32           Kiawairia Primary
33             Ndireti Primary
34               Njunu Primary
35            Kibichoi Primary
36              Loreto Primary
37               Lioki Primary
38              Mayuyu Primary
39               Karia Primary
40            Muchatha Primary
41             Kawaida Primary
42              Karuri Primary
43             Kamondo Primary
44              Ngemwa Primary
45               Riara Primary
46            Gathanji Primary
47    Mungai Chengecha Primary
48             Kiambaa Primary
49             Kibathi Primary
50             Kiababu Primary
51          Githunguri Primary
52            Kahunira Primary
53             Kiairia Primary
54           Muongoiya Primary
55        Chief Wandie Primary
56           Ak Magugu Primary
57       Njenga Karume Primary
58               Ciiko Primary
Name: School, dtype: object

In [9]:

# creating a new columns of  the kichen served for each school 

kiambu_kitchen_schools=["Githunguri Tech Secondary","Ngemwa Primary","Mukua Secondary","Ngemwa Secondary","Gathanji Primary","Gathanji Secondary","Lioki Primary","Kahunira Primary","Ak Magugu Primary","Lioki Secondary","Githunguri Primary","Karia Secondary","Karia Primary", "Ciiko Primary","Kiairia Secondary", "Kiairia Primary","Kahunira Secondary","Kamondo Secondary","Kamondo Primary", "Kiababu Primary"]
def map_kitchen_served(school_name):
    if school_name in kiambu_kitchen_schools:
        return 'kiambu kitchen'
    else:
        return 'Githunguri kitchen'
df["Kitchen"] = df["School"].apply(map_kitchen_served)

In [10]:
df[["School","Kitchen"]]

                      School             Kitchen
0         Gathangari Primary  Githunguri kitchen
1             Kigumo Primary  Githunguri kitchen
2          Kihuririo Primary  Githunguri kitchen
3            Gitombo Primary  Githunguri kitchen
4         Kiambururu Primary  Githunguri kitchen
5          Giathieko Primary  Githunguri kitchen
6              Ihiga Primary  Githunguri kitchen
7             Gatitu Primary  Githunguri kitchen
8              Ngewa Primary  Githunguri kitchen
9             Kanjai Primary  Githunguri kitchen
10           Githiga Primary  Githunguri kitchen
11          Githioro Primary  Githunguri kitchen
12          Mathanja Primary  Githunguri kitchen
13          Matuguta Primary  Githunguri kitchen
14        Kiawaiguru Primary  Githunguri kitchen
15            Gataka Primary  Githunguri kitchen
16           Githima Primary  Githunguri kitchen
17        Gathiruini Primary  Githunguri kitchen
18             Miiri Primary  Githunguri kitchen
19           Riamute Primary  Githunguri kitchen
20            Thuita Primary  Githunguri kitchen
21          Komothai Primary  Githunguri kitchen
22          Mitahato Primary  Githunguri kitchen
23           Kindiga Primary  Githunguri kitchen
24         Gathaithi Primary  Githunguri kitchen
25            Gatina Primary  Githunguri kitchen
26           Kanyore Primary  Githunguri kitchen
27            Kambui Primary  Githunguri kitchen
28           Gathugu Primary  Githunguri kitchen
29            Miguta Primary  Githunguri kitchen
30             Ikinu Primary  Githunguri kitchen
31             Nyaga Primary  Githunguri kitchen
32         Kiawairia Primary  Githunguri kitchen
33           Ndireti Primary  Githunguri kitchen
34             Njunu Primary  Githunguri kitchen
35          Kibichoi Primary  Githunguri kitchen
36            Loreto Primary  Githunguri kitchen
37             Lioki Primary      kiambu kitchen
38            Mayuyu Primary  Githunguri kitchen
39             Karia Primary      kiambu kitchen
40          Muchatha Primary  Githunguri kitchen
41           Kawaida Primary  Githunguri kitchen
42            Karuri Primary  Githunguri kitchen
43           Kamondo Primary      kiambu kitchen
44            Ngemwa Primary      kiambu kitchen
45             Riara Primary  Githunguri kitchen
46          Gathanji Primary      kiambu kitchen
47  Mungai Chengecha Primary  Githunguri kitchen
48           Kiambaa Primary  Githunguri kitchen
49           Kibathi Primary  Githunguri kitchen
50           Kiababu Primary      kiambu kitchen
51        Githunguri Primary      kiambu kitchen
52          Kahunira Primary      kiambu kitchen
53           Kiairia Primary      kiambu kitchen
54         Muongoiya Primary  Githunguri kitchen
55      Chief Wandie Primary  Githunguri kitchen
56         Ak Magugu Primary      kiambu kitchen
57     Njenga Karume Primary  Githunguri kitchen
58             Ciiko Primary      kiambu kitchen

In [11]:
df.groupby("Kitchen")["School"].count()

Kitchen
Githunguri kitchen    48
kiambu kitchen        11
Name: School, dtype: int64

In [12]:
#schools type 
def get_school_type(name):
    name = name.lower()
    if "secondary" in name:
        return "Secondary"
    else:
        return "Primary"

df["School_Type"] = df["School"].apply(get_school_type)

#for good visual  i rearrabge the columns so school type can be be next to school name
cols = list(df.columns)
cols.insert(2, cols.pop(cols.index("School_Type")))
df = df[cols]

In [13]:
df.head(5)

,Kitchen,School,School_Type,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,Githunguri kitchen,Gathangari Primary,Primary,2026-01-05,Rice and GG,220,219,200,19.0,0,...,0.0,NaN,"5 Jan 2026, 12:40:55","5 Jan 2026, 13:30:06",NaN,Food was delicious and hot,Queue was smoothly managed by the T.O.D,Being the first day in school it was 17,Successful taps was 219.Kids did not report we...,@Pauline Gatimu
1,Githunguri kitchen,Kigumo Primary,Primary,2026-01-05,White Rice and GreenGrams,110,125,106,19.0,0,...,0.0,NaN,"5 Jan 2026, 12:40:35","5 Jan 2026, 13:20:40",NaN,Food was delicious,Line management was orderly assisted by the te...,We had 14 failed taps parents forgot to top up,"We had 125 actual meals served,most kids were ...",@S C PCEA Kigumo Comprehensive School
2,Githunguri kitchen,Kihuririo Primary,Primary,2026-01-05,Rice and Gg,330,301,254,47.0,0,...,0.0,NaN,"5 Jan 2026, 12:50:43","5 Jan 2026, 14:00:49",NaN,The food was delicious,Line management was okay,Failed taps were 15,Successful taps were 254,@kihuririo primary
3,Githunguri kitchen,Gitombo Primary,Primary,2026-01-05,White rice and Green grams,90,126,111,15.0,0,...,0.0,NaN,"5 Jan 2026, 12:50:36","5 Jan 2026, 13:23:43",NaN,Food was delicious.,Queue was manageable.,Failed taps were 8 some parents forgot to top ...,Actual meal served today was 126 most kids rep...,@Veronica Mwaura -S/C- Gitombo primary
4,Githunguri kitchen,Kiambururu Primary,Primary,2026-01-05,White Rice and GG,180,167,148,19.0,0,...,0.0,NaN,"5 Jan 2026, 12:50:40","5 Jan 2026, 13:57:50",NaN,Food was delicious,Line management was smooth,Failed taps were 9.Some parents hadn't topped ...,Actual meals served was 167.This is because th...,@Kiambururu Comprehensive School

In [14]:
#region columns
Githunguri_1=["Kahunira Secondary","Ciiko Primary","Mukuyu Secondary","Kiawaiguru Primary","Gitiha Secondary","Kiawairia Primary","Matuguta Primary","Kindiga Primary","Gathiruini Primary","Kahunira Primary","Njunu Primary","Miiri Secondary","Githima Primary","Kiawairia Secondary","Miguta Secondary","Githioro Primary","Ihiga Primary","Kiambururu Primary","Gathaithi Secondary","Gathaithi Primary","Gatina Primary","Mathanja Primary","Gitombo Primary","Matuguta Secondary","Kanyore Primary","Kiambururu Secondary","Gikang'A Kageche Secondary","Gataka Primary","Githiga Primary","Kiababu Primary","Githunguri Tech Secondary","Gatitu Primary",]
Githunguri_2=["Karia Secondary","William Ng'Iru Secondary","Mukua Secondary","Mitahato Secondary","Ndireti Secondary","Mitahato Primary","Riamute Primary","Kanjai Primary","Komothai Primary","Miguta Primary","Ngewa Primary","Nyaga Secondary","Nyaga Primary","Giathieko Primary","Kambui Primary","Kanjai Secondary","Ndireti Primary","Miiri Primary","Ikinu Primary","Ak Magugu Primary","Kamondo Secondary","Kamondo Primary","","Lioki Primary","Gathangari Primary","Ngemwa Primary","Kiairia Secondary","Kiairia Primary","Githunguri Primary","Karia Primary","Lioki Secondary","Gathanji Secondary","Gathanji Primary","Ngemwa Secondary"]
Ruiru_Githunguri=["Gathugu Primary","Thuita Secondary","Kibichoi Primary","Gathugu Secondary","Kagema Secondary","Thuita Primary","Kigumo Secondary","Kigumo Primary","Kihuririo Primary","Kagema Primary"]
#new column for month 
def assign_cluster(school):
    if school in Githunguri_1:
        return "Githunguri 1"
    elif school in Githunguri_2:
        return "Githunguri 2"
    elif school in Ruiru_Githunguri:
        return "Ruiru-Githunguri"
    else:
        return "Other"

# Apply the function to the School column
df["Cluster"] = df["School"].apply(assign_cluster)

In [15]:
df[["School", "Cluster"]]

                      School           Cluster
0         Gathangari Primary      Githunguri 2
1             Kigumo Primary  Ruiru-Githunguri
2          Kihuririo Primary  Ruiru-Githunguri
3            Gitombo Primary      Githunguri 1
4         Kiambururu Primary      Githunguri 1
5          Giathieko Primary      Githunguri 2
6              Ihiga Primary      Githunguri 1
7             Gatitu Primary      Githunguri 1
8              Ngewa Primary      Githunguri 2
9             Kanjai Primary      Githunguri 2
10           Githiga Primary      Githunguri 1
11          Githioro Primary      Githunguri 1
12          Mathanja Primary      Githunguri 1
13          Matuguta Primary      Githunguri 1
14        Kiawaiguru Primary      Githunguri 1
15            Gataka Primary      Githunguri 1
16           Githima Primary      Githunguri 1
17        Gathiruini Primary      Githunguri 1
18             Miiri Primary      Githunguri 2
19           Riamute Primary      Githunguri 2
20            Thuita Primary  Ruiru-Githunguri
21          Komothai Primary      Githunguri 2
22          Mitahato Primary      Githunguri 2
23           Kindiga Primary      Githunguri 1
24         Gathaithi Primary      Githunguri 1
25            Gatina Primary      Githunguri 1
26           Kanyore Primary      Githunguri 1
27            Kambui Primary      Githunguri 2
28           Gathugu Primary  Ruiru-Githunguri
29            Miguta Primary      Githunguri 2
30             Ikinu Primary      Githunguri 2
31             Nyaga Primary      Githunguri 2
32         Kiawairia Primary      Githunguri 1
33           Ndireti Primary      Githunguri 2
34             Njunu Primary      Githunguri 1
35          Kibichoi Primary  Ruiru-Githunguri
36            Loreto Primary             Other
37             Lioki Primary      Githunguri 2
38            Mayuyu Primary             Other
39             Karia Primary      Githunguri 2
40          Muchatha Primary             Other
41           Kawaida Primary             Other
42            Karuri Primary             Other
43           Kamondo Primary      Githunguri 2
44            Ngemwa Primary      Githunguri 2
45             Riara Primary             Other
46          Gathanji Primary      Githunguri 2
47  Mungai Chengecha Primary             Other
48           Kiambaa Primary             Other
49           Kibathi Primary             Other
50           Kiababu Primary      Githunguri 1
51        Githunguri Primary      Githunguri 2
52          Kahunira Primary      Githunguri 1
53           Kiairia Primary      Githunguri 2
54         Muongoiya Primary             Other
55      Chief Wandie Primary             Other
56         Ak Magugu Primary      Githunguri 2
57     Njenga Karume Primary             Other
58             Ciiko Primary      Githunguri 1

In [16]:
df["School"]

0           Gathangari Primary
1               Kigumo Primary
2            Kihuririo Primary
3              Gitombo Primary
4           Kiambururu Primary
5            Giathieko Primary
6                Ihiga Primary
7               Gatitu Primary
8                Ngewa Primary
9               Kanjai Primary
10             Githiga Primary
11            Githioro Primary
12            Mathanja Primary
13            Matuguta Primary
14          Kiawaiguru Primary
15              Gataka Primary
16             Githima Primary
17          Gathiruini Primary
18               Miiri Primary
19             Riamute Primary
20              Thuita Primary
21            Komothai Primary
22            Mitahato Primary
23             Kindiga Primary
24           Gathaithi Primary
25              Gatina Primary
26             Kanyore Primary
27              Kambui Primary
28             Gathugu Primary
29              Miguta Primary
30               Ikinu Primary
31               Nyaga Primary
32           Kiawairia Primary
33             Ndireti Primary
34               Njunu Primary
35            Kibichoi Primary
36              Loreto Primary
37               Lioki Primary
38              Mayuyu Primary
39               Karia Primary
40            Muchatha Primary
41             Kawaida Primary
42              Karuri Primary
43             Kamondo Primary
44              Ngemwa Primary
45               Riara Primary
46            Gathanji Primary
47    Mungai Chengecha Primary
48             Kiambaa Primary
49             Kibathi Primary
50             Kiababu Primary
51          Githunguri Primary
52            Kahunira Primary
53             Kiairia Primary
54           Muongoiya Primary
55        Chief Wandie Primary
56           Ak Magugu Primary
57       Njenga Karume Primary
58               Ciiko Primary
Name: School, dtype: object

In [17]:
#new column for month 
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month
df["Month"] = df["Date"].dt.month_name()

cols = list(df.columns)
cols.insert(3, cols.pop(cols.index("Month")))
df = df[cols]

In [18]:
def get_rice_variant(menu_item):
    if pd.isna(menu_item):
        return ""
    menu_item = menu_item.lower()
    if "masala" in menu_item:
        return "Masala"
    elif "tumeric" in menu_item:
        return "Tumeric"
    else:
        return "White"

df["Rice_variant"] = df["Menu"].apply(get_rice_variant)
# For column reordering to be next to menu 
cols = list(df.columns)
cols.insert(5, cols.pop(cols.index("Rice_variant")))
df = df[cols]

In [ ]:
def clean_menu(name):
    if pd.isna(name):
        return None
    
    # Normalize casing and whitespace
    name = name.strip().title()
    
    # Replace connectors
    name = name.replace("&", "And")
    
    # Standardize synonyms/abbreviations
    name = re.sub(r"\bGg\b", "Greengrams", name, flags=re.IGNORECASE)
    name = re.sub(r"\bG\.G\b", "Greengrams", name, flags=re.IGNORECASE)
    name = re.sub(r"Riceandgg", "Rice and Greengrams", name, flags=re.IGNORECASE)
    name = name.replace("Green Gram", "Greengrams")
    name = name.replace("Green Grams", "Greengrams")
    name = name.replace("Greengram", "Greengrams")
    
    # If "Rice" exists, discard everything before it
    if "Rice" in name:
        idx = name.find("Rice")
        name = name[idx:]
    
    # Canonical mapping
    if "Greengrams" in name:
        return "Rice and Greengrams"
    elif "Beans" in name:
        return "Rice and Beans"
    elif "Western" in name:
        return "Rice and Western"
    
    # If no keyword matched, return substring after Rice
    return name

In [28]:
df["Menu"] = df["Menu"].apply(clean_menu)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Kitchen                       59 non-null     object
 1   School                        59 non-null     object
 2   School_Type                   59 non-null     object
 3   Month                         58 non-null     object
 4   Date                          58 non-null     datetime64[ns]
 5   Rice_variant                  59 non-null     object
 6   Menu                          58 non-null     object
 7   Projected_Kids                59 non-null     int64
 8   Actual_Meals_Served           59 non-null     int64
 9   Successful_Taps               59 non-null     int64
 10  F4E_Supported_Kids            58 non-null     float64
 11  Teachers                      59 non-null     int64
 12  Staff_Meals                   59 non-null     int64
 13  Failed_Taps                   59 non-null     int64
 14  New_Registrations             59 non-null     int64
 15  New_Tags_Replaced             59 non-null     int64
 16  Rice_Remaining                59 non-null     float64
 17  B_W_G_Remaining               59 non-null     float64
 18  Missed_Food                   22 non-null     float64
 19  Next_Day_Projection_Students  59 non-null     int64
 20  Next_Day_Projection_Teachers  58 non-null     float64
 21  Next_Day_Projection_Staff     23 non-null     float64
 22  Start_Taping                  59 non-null     object
 23  Stop_Taping                   59 non-null     object
 24  Projection_Comment            23 non-null     object
 25  Comment_1                     59 non-null     object
 26  Comment_2                     59 non-null     object
 27  Comment_3                     59 non-null     object
 28  Comment_4                     59 non-null     object
 29  Reported_By                   59 non-null     object
 30  Cluster                       59 non-null     object
dtypes: datetime64[ns](1), float64(6), int64(9), object(15)
memory usage: 14.4+ KB

In [29]:
df[["Date","School","School_Type","Menu","Rice_variant","Kitchen"]].nunique()

Date             1
School          59
School_Type      1
Menu             2
Rice_variant     2
Kitchen          2
dtype: int64

In [30]:
df['Menu'].unique()

array(['Rice and Greengrams', 'Riceandgg', None], dtype=object)

In [122]:
# Convert to datetime
df["Start_Taping"] = pd.to_datetime(df["Start_Taping"], format="%d %b %Y, %H:%M:%S")
df["Stop_Taping"] = pd.to_datetime(df["Stop_Taping"], format="%d %b %Y, %H:%M:%S")
# Compute duration
lunch_time= df["Stop_Taping"] - df["Start_Taping"]
df["Lunch_Time_Min"] = (lunch_time.dt.total_seconds() / 60).round(0).astype('Int64')  # Convert to minutes and round


cols = list(df.columns)
# moving Lunch_Time_Min to index 23 nest to the parent columns
cols.insert(23, cols.pop(cols.index("Lunch_Time_Min")))

# Reassign DataFrame with new order
df = df[cols]

In [123]:

pd.set_option("display.max_rows", None)
df.head(3)

,Kitchen,School,School_Type,Month,Date,Rice_variant,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,...,Start_Taping,Lunch_Time_Min,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By,Cluster
0,kiambu kitchen,Kahunira Primary,Primary,January,2026-01-15,White,Rice and Greengrams,690,720,661,...,2026-01-15 12:40:45,55,2026-01-15 13:35:53,Being on Friday turn out is usually low.,"Food was delicious, students enjoyed bananas.",Queue management was well executed by teacher ...,Failed taps increased slightly from 21 to 22.,Actual meals served today increased greatly fr...,@Mwangi Mary Kahunira Comprehensive,Githunguri 1
1,kiambu kitchen,Ciiko Primary,Primary,January,2026-01-15,White,Rice and Greengrams,960,965,904,...,2026-01-15 12:29:01,61,2026-01-15 13:30:08,We expect the same turnout as today.,Food was hot and delicious,The queue was managed by the teacher on duty,Failed taps decreased from 15 to 9,Successful taps increased from 955 to 965.,@Ciiko Comprehensive school -SL- Samy Migwi,Githunguri 1
2,kiambu kitchen,Kahunira Secondary,Secondary,January,2026-01-15,White,Rice and Greengrams,140,149,149,...,2026-01-15 13:00:23,30,2026-01-15 13:30:36,Expecting grade 10 students to,Food was delicious,Queue was well managed by TOD,"Failed taps increased from 2 to 4, some parent...","Meals served today decreased from 150 to 149, ...",@Tapper kahunira secondary,Githunguri 1

In [124]:
df.head(10)

,Kitchen,School,School_Type,Month,Date,Rice_variant,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,...,Start_Taping,Lunch_Time_Min,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By,Cluster
0,kiambu kitchen,Kahunira Primary,Primary,January,2026-01-15,White,Rice and Greengrams,690,720,661,...,2026-01-15 12:40:45,55,2026-01-15 13:35:53,Being on Friday turn out is usually low.,"Food was delicious, students enjoyed bananas.",Queue management was well executed by teacher ...,Failed taps increased slightly from 21 to 22.,Actual meals served today increased greatly fr...,@Mwangi Mary Kahunira Comprehensive,Githunguri 1
1,kiambu kitchen,Ciiko Primary,Primary,January,2026-01-15,White,Rice and Greengrams,960,965,904,...,2026-01-15 12:29:01,61,2026-01-15 13:30:08,We expect the same turnout as today.,Food was hot and delicious,The queue was managed by the teacher on duty,Failed taps decreased from 15 to 9,Successful taps increased from 955 to 965.,@Ciiko Comprehensive school -SL- Samy Migwi,Githunguri 1
2,kiambu kitchen,Kahunira Secondary,Secondary,January,2026-01-15,White,Rice and Greengrams,140,149,149,...,2026-01-15 13:00:23,30,2026-01-15 13:30:36,Expecting grade 10 students to,Food was delicious,Queue was well managed by TOD,"Failed taps increased from 2 to 4, some parent...","Meals served today decreased from 150 to 149, ...",@Tapper kahunira secondary,Githunguri 1
3,kiambu kitchen,Githunguri Tech Secondary,Secondary,January,2026-01-15,White,Rice and Greengrams,162,157,157,...,2026-01-15 13:30:41,30,2026-01-15 14:00:49,We expect a rise of successful taps tomorrow,Food was delicious and warm,Queue was well manageable by teacher on duty,Failed taps today was 5 which is a increase co...,Actual meal served today was 157 which is a in...,"@Yvonne mugure, Githunguri Technical And Secon...",Githunguri 1
4,Githunguri kitchen,Kiawairia Primary,Primary,January,2026-01-15,White,Rice and Greengrams,130,129,113,...,2026-01-15 12:00:46,90,2026-01-15 13:30:52,NaN,Food was delicious,Lines were neat and ordely,We had 4 failed taps an increase from 1 some p...,We had 113 successful taps a decrease from 116...,@Mary kimani SC kiawairia comprehensive school,Githunguri 1
5,Githunguri kitchen,Gathiruini Primary,Primary,January,2026-01-15,White,Rice and Greengrams,245,246,220,...,2026-01-15 12:30:47,60,2026-01-15 13:30:57,NaN,Lunch was delicious,Line management was good with help of teacher ...,Failed taps today were 3 an increase from 2 th...,Actual meal served today were 246 an increase ...,@Catherine Wanjiru,Githunguri 1
6,Githunguri kitchen,Kiawaiguru Primary,Primary,January,2026-01-15,White,Rice and Greengrams,220,219,200,...,2026-01-15 12:30:00,50,2026-01-15 13:20:00,NaN,Food was delicious.,Line transtioned from class to class in an ode...,Failed taps were 0 just like yesterday. I mana...,Actual meals served was 219 just like yesterda...,@KIAWAIGURU PRIMARY SCHOOL,Githunguri 1
7,Githunguri kitchen,Gataka Primary,Primary,January,2026-01-15,White,Rice and Greengrams,290,276,259,...,2026-01-15 12:35:22,65,2026-01-15 13:40:44,NaN,The food was delicious,The queue was well managed by the school coord...,"The number of failed taps remained at 7, we re...",The number of actual meals dropped from 289 to...,@Catholic archdiocese of Nairobi Gataka primar...,Githunguri 1
8,Githunguri kitchen,Gikang'A Kageche Secondary,Secondary,January,2026-01-15,White,Rice and Greengrams,260,260,260,...,2026-01-15 13:10:49,33,2026-01-15 13:43:58,NaN,Food was delicious,Queue was smoothly managed by the help of TOD,Today's failed taps increased from 4 to 7..par...,Today's successful taps was 260 an increase fr...,@Pauline Gatimu,Githunguri 1
9,Githunguri kitchen,Ihiga Primary,Primary,January,2026-01-15,White,Rice and Greengrams,170,157,144,...,2026-01-15 12:40:01,30,2026-01-15 13:10:07,NaN,Food was Hot.,Queues were manageable.,Failed taps were 5 an increase from yesterday'...,Successful taps 157 a decrease from yesterday'...,@Naomi SC-Ihiga Comprehensive,Githunguri 1

In [125]:
df.nunique()

Kitchen                          2
School                          30
School_Type                      2
Month                            1
Date                             1
Rice_variant                     1
Menu                             2
Projected_Kids                  28
Actual_Meals_Served             29
Successful_Taps                 30
F4E_Supported_Kids              17
Teachers                         4
Staff_Meals                      4
Failed_Taps                     18
New_Registrations                7
New_Tags_Replaced               12
Rice_Remaining                   6
B_W_G_Remaining                  6
Missed_Food                      1
Next_Day_Projection_Students    24
Next_Day_Projection_Teachers     5
Next_Day_Projection_Staff        4
Start_Taping                    29
Lunch_Time_Min                  21
Stop_Taping                     30
Projection_Comment               5
Comment_1                       19
Comment_2                       28
Comment_3                       30
Comment_4                       30
Reported_By                     29
Cluster                          2
dtype: int64

In [126]:
#lets use os 
output_dir = r"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed"
base = date.replace(".csv", "")
output_path = os.path.join(output_dir, f"{base}_clean.csv")
df.to_csv(output_path, index=False)
print("Saved:", output_path)

Saved: C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed\15_01_26_clean.csv