In [5]:
import pandas as pd
import numpy as np
import re
import plotly.graph_objects as go
import plotly.express as px
import os

In [42]:
date="04_02_26.csv"
df=pd.read_csv(fr"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_raw\extarcted_csv\{date}")
print(df.shape)

(75, 27)

In [43]:
df.head()

,Kitchen,School,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,Staff_Meals,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,reports | Feb 4th | View message,AK Magugu Comprehensive School,2/4/2026,White rice and western,430,415,375,40,0,3,...,0,3.0,"4 Feb 2026, 12:25:50","4 Feb 2026, 13:25:55",Normal school day,The food was delicious,The queue was orderly,The number of failed taps reduced from 16 to 1...,The number of successful taps reduced from 406...,@SC Margaret Maigua - Ak magugu comprehensive
1,NaN,Kamondo Secondary School,2/4/2026,White rice and western,135,123,123,0,0,2,...,0,2.0,"4 Feb 2026, 13:30:52","4 Feb 2026, 14:00:57",Expecting high turn up also the insufficient a...,Food was well cooked,Queue management was well managed with the hel...,Decrease from 6 to 4 as accounts were recharged,Slight decrease from 124 to 123 as some accoun...,"@Esther, Tapper kamondo secondary school"
2,NaN,Kamondo Primary and Junior School,2/4/2026,White rice western and Mangoes,350,364,327,37,0,3,...,0,3.0,"4 Feb 2026, 12:40:33","4 Feb 2026, 13:30:44",We expect turn up to decrease slightly,The food was well cooked and kids enjoyed the ...,The queue was well managed by the ToD,13 Failed taps a rise from 07 as respective pa...,327 Successful Taps a rise from 307 as turn up...,@SCwangengi -Kamondo primary school
3,NaN,P.C.E.A Karia Secondary School,2/4/2026,White rice and western,50,48,48,0,4,2,...,5,2.0,"4 Feb 2026, 13:15:19","4 Feb 2026, 13:35:26",Qe expect a higher turnout tomorrow,Food was delicious and enough,Line was well managed,The number of failed taps has remained the sam...,The number of successful taps has increased fr...,@Simon Tapper Karia secondary
4,NaN,Lioki Comprehensive School,2/4/2026,white rice and Western,155,156,137,19,0,2,...,0,2.0,"4 Feb 2026, 13:00:12","4 Feb 2026, 13:50:19",we expect a better turn out tomorrow,food was hot and delicious,queue management was well done by the School C...,failed taps decreased from 8 to 3 as parents r...,successful taps increased from 133 to 137 as 4...,@SC Phoebe - Lioki Primary school

In [44]:
df.isnull().sum()

Kitchen                         74
School                           0
Date                             0
Menu                             0
Projected_Kids                   0
Actual_Meals_Served              0
Successful_Taps                  0
F4E_Supported_Kids               0
Teachers                         0
Staff_Meals                      0
Failed_Taps                      0
New_Registrations                0
New_Tags_Replaced                0
Rice_Remaining                   1
B_W_G_Remaining                  0
Missed_Food                     55
Next_Day_Projection_Students     0
Next_Day_Projection_Teachers     0
Next_Day_Projection_Staff       55
Start_Taping                     0
Stop_Taping                      0
Projection_Comment              55
Comment_1                        0
Comment_2                        1
Comment_3                        1
Comment_4                        1
Reported_By                      0
dtype: int64

In [10]:
#stem and map the school names
df["School"]

0        AK Magugu Comprehensive School
1              Kamondo Secondary School
2     Kamondo Primary and Junior School
3        P.C.E.A Karia Secondary School
4            Lioki Comprehensive School
                    ...
70              Thuita Secondary School
71              Mitahato Primary School
72             Ndireti Secondary School
73       PCEA Mitahato Secondary School
74               Mukua Secondary School
Name: School, Length: 75, dtype: object

In [45]:
def clean_school_name(name):
    # Fixing  this typos for mathanja 
    name = name.replace("Primry", "Primary")
    
    # Replacing "Comprehensive" with "Primary"
    name = name.replace("Comprehensive", "Primary")
    
    # chopping the word "School" 
    name = re.sub(r"\b[Ss]chool\b", "", name)
    
    # remaoving  Junior Secondary" or similar suffixes
    name = re.sub(r"& Junior Secondary", "", name, flags=re.IGNORECASE)
    
    
    # Simplifying Catholic Archdiocese   and pcea
    if "Gataka" in name:
        return "Gataka Primary"
    if "Mitahato" in name:
        if "Secondary" in name:
            return "Mitahato Secondary"
        else:
            return "Mitahato Primary"
    if "Matuguta" in name:
        if "Secondary" in name:
            return "Matuguta Secondary"
        else:
            return "Matuguta Primary"
    if "Riamute" in name:
        return "Riamute Primary"
    if "Ngemwa" in name:
        if "Secondary" in name:
            return "Ngemwa Secondary"
        else:
            return "Ngemwa Primary"
    if "Lioki" in name:
        if "Secondary" in name:
            return "Lioki Secondary"
        else:
            return "Lioki Primary"
    if "Karia" in name:
        if "Secondary" in name:
            return "Karia Secondary"
        else:
            return "Karia Primary"
    if "Kamondo" in name:
        if "Secondary" in name:
            return "Kamondo Secondary"
        else:
            return "Kamondo Primary"
    if "Githunguri" in name:
        if "Secondary" in name:
            return "Githunguri Tech Secondary"
        else:
            return "Githunguri Primary"
    
    
    #    spacing and capitalization
    name = " ".join(name.split())  # remove extra spaces
    name = name.title()            # standardize case
    
    return name.strip()

In [46]:
df["School"] = df["School"].apply(clean_school_name)

In [47]:
pd.describe_option("display.max_rows")
pd.set_option("display.max_rows", 100)

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: None]

In [48]:
df['School']

0              Ak Magugu Primary
1              Kamondo Secondary
2                Kamondo Primary
3                Karia Secondary
4                  Lioki Primary
5                 Ngemwa Primary
6              Kiairia Secondary
7               Ngemwa Secondary
8                Kiairia Primary
9             Githunguri Primary
10                 Karia Primary
11               Lioki Secondary
12            Gathanji Secondary
13              Gathanji Primary
14            Kahunira Secondary
15                 Ciiko Primary
16              Kahunira Primary
17               Kiababu Primary
18     Githunguri Tech Secondary
19                Gatitu Primary
20               Gathugu Primary
21           Pcea Kagema Primary
22            Gathangari Primary
23      William Ng'Iru Secondary
24               Githiga Primary
25                Gataka Primary
26    Gikang'A Kageche Secondary
27          Kiambururu Secondary
28               Kanyore Primary
29            Matuguta Secondary
30                 Ikinu Primary
31               Gitombo Primary
32              Mathanja Priamry
33                Gatina Primary
34                 Miiri Primary
35             Gathaithi Primary
36           Gathaithi Secondary
37               Ndireti Primary
38            Kiambururu Primary
39                 Ihiga Primary
40              Kanjai Secondary
41                Kambui Primary
42              Githioro Primary
43              Mukuyu Secondary
44              Miguta Secondary
45           Kiawairia Secondary
46               Githima Primary
47               Miiri Secondary
48                 Njunu Primary
49              Kagema Secondary
50             Gathugu Secondary
51             Giathieko Primary
52             Kihuririo Primary
53                 Nyaga Primary
54               Nyaga Secondary
55            Gathiruini Primary
56                 Ngewa Primary
57               Kindiga Primary
58                Miguta Primary
59              Komothai Primary
60              Matuguta Primary
61                Kanjai Primary
62               Riamute Primary
63             Kiawairia Primary
64              Kibichoi Primary
65              Gitiha Secondary
66                Kigumo Primary
67              Kigumo Secondary
68                Thuita Primary
69            Kiawaiguru Primary
70              Thuita Secondary
71              Mitahato Primary
72             Ndireti Secondary
73            Mitahato Secondary
74               Mukua Secondary
Name: School, dtype: object

In [49]:

# creating a new columns of  the kichen served for each school 

kiambu_kitchen_schools=["Githunguri Tech Secondary","Ngemwa Primary","Mukua Secondary","Ngemwa Secondary","Gathanji Primary","Gathanji Secondary","Lioki Primary","Kahunira Primary","Ak Magugu Primary","Lioki Secondary","Githunguri Primary","Karia Secondary","Karia Primary", "Ciiko Primary","Kiairia Secondary", "Kiairia Primary","Kahunira Secondary","Kamondo Secondary","Kamondo Primary", "Kiababu Primary"]
def map_kitchen_served(school_name):
    if school_name in kiambu_kitchen_schools:
        return 'kiambu kitchen'
    else:
        return 'Githunguri'
df["Kitchen"] = df["School"].apply(map_kitchen_served)

In [50]:
df[["School","Kitchen"]]

                        School         Kitchen
0            Ak Magugu Primary  kiambu kitchen
1            Kamondo Secondary  kiambu kitchen
2              Kamondo Primary  kiambu kitchen
3              Karia Secondary  kiambu kitchen
4                Lioki Primary  kiambu kitchen
5               Ngemwa Primary  kiambu kitchen
6            Kiairia Secondary  kiambu kitchen
7             Ngemwa Secondary  kiambu kitchen
8              Kiairia Primary  kiambu kitchen
9           Githunguri Primary  kiambu kitchen
10               Karia Primary  kiambu kitchen
11             Lioki Secondary  kiambu kitchen
12          Gathanji Secondary  kiambu kitchen
13            Gathanji Primary  kiambu kitchen
14          Kahunira Secondary  kiambu kitchen
15               Ciiko Primary  kiambu kitchen
16            Kahunira Primary  kiambu kitchen
17             Kiababu Primary  kiambu kitchen
18   Githunguri Tech Secondary  kiambu kitchen
19              Gatitu Primary      Githunguri
20             Gathugu Primary      Githunguri
21         Pcea Kagema Primary      Githunguri
22          Gathangari Primary      Githunguri
23    William Ng'Iru Secondary      Githunguri
24             Githiga Primary      Githunguri
25              Gataka Primary      Githunguri
26  Gikang'A Kageche Secondary      Githunguri
27        Kiambururu Secondary      Githunguri
28             Kanyore Primary      Githunguri
29          Matuguta Secondary      Githunguri
30               Ikinu Primary      Githunguri
31             Gitombo Primary      Githunguri
32            Mathanja Priamry      Githunguri
33              Gatina Primary      Githunguri
34               Miiri Primary      Githunguri
35           Gathaithi Primary      Githunguri
36         Gathaithi Secondary      Githunguri
37             Ndireti Primary      Githunguri
38          Kiambururu Primary      Githunguri
39               Ihiga Primary      Githunguri
40            Kanjai Secondary      Githunguri
41              Kambui Primary      Githunguri
42            Githioro Primary      Githunguri
43            Mukuyu Secondary      Githunguri
44            Miguta Secondary      Githunguri
45         Kiawairia Secondary      Githunguri
46             Githima Primary      Githunguri
47             Miiri Secondary      Githunguri
48               Njunu Primary      Githunguri
49            Kagema Secondary      Githunguri
50           Gathugu Secondary      Githunguri
51           Giathieko Primary      Githunguri
52           Kihuririo Primary      Githunguri
53               Nyaga Primary      Githunguri
54             Nyaga Secondary      Githunguri
55          Gathiruini Primary      Githunguri
56               Ngewa Primary      Githunguri
57             Kindiga Primary      Githunguri
58              Miguta Primary      Githunguri
59            Komothai Primary      Githunguri
60            Matuguta Primary      Githunguri
61              Kanjai Primary      Githunguri
62             Riamute Primary      Githunguri
63           Kiawairia Primary      Githunguri
64            Kibichoi Primary      Githunguri
65            Gitiha Secondary      Githunguri
66              Kigumo Primary      Githunguri
67            Kigumo Secondary      Githunguri
68              Thuita Primary      Githunguri
69          Kiawaiguru Primary      Githunguri
70            Thuita Secondary      Githunguri
71            Mitahato Primary      Githunguri
72           Ndireti Secondary      Githunguri
73          Mitahato Secondary      Githunguri
74             Mukua Secondary  kiambu kitchen

In [30]:
df.groupby("Kitchen")["School"].count()

Kitchen
Githunguri        55
kiambu kitchen    20
Name: School, dtype: int64

In [51]:
#schools type 
def get_school_type(name):
    name = name.lower()
    if "secondary" in name:
        return "Secondary"
    else:
        return "Primary"

df["School_Type"] = df["School"].apply(get_school_type)

#for good visual  i rearrabge the columns so school type can be be next to school name
cols = list(df.columns)
cols.insert(2, cols.pop(cols.index("School_Type")))
df = df[cols]

In [65]:
df.head(5)

,Kitchen,School,School_Type,Month,Date,Rice_variant,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,...,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By,Cluster
0,kiambu kitchen,Ak Magugu Primary,Primary,February,2026-02-04,White,Rice and Western,430,415,375,...,3.0,"4 Feb 2026, 12:25:50","4 Feb 2026, 13:25:55",Normal school day,The food was delicious,The queue was orderly,The number of failed taps reduced from 16 to 1...,The number of successful taps reduced from 406...,@SC Margaret Maigua - Ak magugu comprehensive,Githunguri_2
1,kiambu kitchen,Kamondo Secondary,Secondary,February,2026-02-04,White,Rice and Western,135,123,123,...,2.0,"4 Feb 2026, 13:30:52","4 Feb 2026, 14:00:57",Expecting high turn up also the insufficient a...,Food was well cooked,Queue management was well managed with the hel...,Decrease from 6 to 4 as accounts were recharged,Slight decrease from 124 to 123 as some accoun...,"@Esther, Tapper kamondo secondary school",Other
2,kiambu kitchen,Kamondo Primary,Primary,February,2026-02-04,White,Rice and Western,350,364,327,...,3.0,"4 Feb 2026, 12:40:33","4 Feb 2026, 13:30:44",We expect turn up to decrease slightly,The food was well cooked and kids enjoyed the ...,The queue was well managed by the ToD,13 Failed taps a rise from 07 as respective pa...,327 Successful Taps a rise from 307 as turn up...,@SCwangengi -Kamondo primary school,Githunguri_2
3,kiambu kitchen,Karia Secondary,Secondary,February,2026-02-04,White,Rice and Western,50,48,48,...,2.0,"4 Feb 2026, 13:15:19","4 Feb 2026, 13:35:26",Qe expect a higher turnout tomorrow,Food was delicious and enough,Line was well managed,The number of failed taps has remained the sam...,The number of successful taps has increased fr...,@Simon Tapper Karia secondary,Githunguri_2
4,kiambu kitchen,Lioki Primary,Primary,February,2026-02-04,White,Rice and Western,155,156,137,...,2.0,"4 Feb 2026, 13:00:12","4 Feb 2026, 13:50:19",we expect a better turn out tomorrow,food was hot and delicious,queue management was well done by the School C...,failed taps decreased from 8 to 3 as parents r...,successful taps increased from 133 to 137 as 4...,@SC Phoebe - Lioki Primary school,Githunguri_2

In [ ]:
#region columns
Githunguri_1=["Kahunira Secondary","Ciiko Primary","Mukuyu Secondary","Kiawaiguru Primary","Gitiha Secondary","Kiawairia Primary","Matuguta Primary","Kindiga Primary","Gathiruini Primary","Kahunira Primary","Njunu Primary","Miiri Secondary","Githima Primary","Kiawairia Secondary","Miguta Secondary","Githioro Primary","Ihiga Primary","Kiambururu Primary","Gathaithi Secondary","Gathaithi Primary","Gatina Primary","Mathanja Primary","Gitombo Primary","Matuguta Secondary","Kanyore Primary","Kiambururu Secondary","Gikang'A Kageche Secondary","Gataka Primary","Githiga Primary","Kiababu Primary","Githunguri Tech Secondary","Gatitu Primary",]
Githunguri_2=["Karia Secondary","William Ng'Iru Secondary","Mukua Secondary","Mitahato Secondary","Ndireti Secondary","Mitahato Primary","Riamute Primary","Kanjai Primary","Komothai Primary","Miguta Primary","Ngewa Primary","Nyaga Secondary","Nyaga Primary","Giathieko Primary","Kambui Primary","Kanjai Secondary","Ndireti Primary","Miiri Primary","Ikinu Primary","Ak Magugu Primary"," Kamondo Secondary","Kamondo Primary","","Lioki Primary","Gathangari Primary","Ngemwa Primary","Kiairia Secondary","Kiairia Primary","Githunguri Primary","Karia Primary","Lioki Secondary","Gathanji Secondary","Gathanji Primary"]
Ruiru_Githunguri=["Gathugu Primary","Thuita Secondary","Kibichoi Primary","Gathugu Secondary","Kagema Secondary","Thuita Primary","Kigumo Secondary","Kihuririo Primary","Kagema Primary"]
#new column for month 
def assign_cluster(school):
    if school in Githunguri_1:
        return "Githunguri_1"
    elif school in Githunguri_2:
        return "Githunguri_2"
    elif school in Ruiru_Githunguri:
        return "Ruiru_Githunguri"
    else:
        return "Other"

# Apply the function to the School column
df["Cluster"] = df["School"].apply(assign_cluster)

In [69]:
df[["School", "Cluster"]]

                        School           Cluster
0            Ak Magugu Primary      Githunguri_2
1            Kamondo Secondary      Githunguri_2
2              Kamondo Primary      Githunguri_2
3              Karia Secondary      Githunguri_2
4                Lioki Primary      Githunguri_2
5               Ngemwa Primary      Githunguri_2
6            Kiairia Secondary      Githunguri_2
7             Ngemwa Secondary             Other
8              Kiairia Primary             Other
9           Githunguri Primary      Githunguri_2
10               Karia Primary      Githunguri_2
11             Lioki Secondary      Githunguri_2
12          Gathanji Secondary      Githunguri_2
13            Gathanji Primary      Githunguri_2
14          Kahunira Secondary      Githunguri_1
15               Ciiko Primary      Githunguri_1
16            Kahunira Primary      Githunguri_1
17             Kiababu Primary      Githunguri_1
18   Githunguri Tech Secondary      Githunguri_1
19              Gatitu Primary      Githunguri_1
20             Gathugu Primary  Ruiru_Githunguri
21         Pcea Kagema Primary             Other
22          Gathangari Primary      Githunguri_2
23    William Ng'Iru Secondary             Other
24             Githiga Primary      Githunguri_1
25              Gataka Primary      Githunguri_1
26  Gikang'A Kageche Secondary      Githunguri_1
27        Kiambururu Secondary      Githunguri_1
28             Kanyore Primary      Githunguri_1
29          Matuguta Secondary      Githunguri_1
30               Ikinu Primary      Githunguri_2
31             Gitombo Primary      Githunguri_1
32            Mathanja Priamry             Other
33              Gatina Primary      Githunguri_1
34               Miiri Primary             Other
35           Gathaithi Primary      Githunguri_1
36         Gathaithi Secondary      Githunguri_1
37             Ndireti Primary      Githunguri_2
38          Kiambururu Primary      Githunguri_1
39               Ihiga Primary      Githunguri_1
40            Kanjai Secondary      Githunguri_2
41              Kambui Primary      Githunguri_2
42            Githioro Primary      Githunguri_1
43            Mukuyu Secondary      Githunguri_1
44            Miguta Secondary      Githunguri_1
45         Kiawairia Secondary      Githunguri_1
46             Githima Primary      Githunguri_1
47             Miiri Secondary      Githunguri_1
48               Njunu Primary      Githunguri_1
49            Kagema Secondary             Other
50           Gathugu Secondary             Other
51           Giathieko Primary      Githunguri_2
52           Kihuririo Primary  Ruiru_Githunguri
53               Nyaga Primary      Githunguri_2
54             Nyaga Secondary      Githunguri_2
55          Gathiruini Primary      Githunguri_1
56               Ngewa Primary      Githunguri_2
57             Kindiga Primary      Githunguri_1
58              Miguta Primary      Githunguri_2
59            Komothai Primary      Githunguri_2
60            Matuguta Primary      Githunguri_1
61              Kanjai Primary      Githunguri_2
62             Riamute Primary      Githunguri_2
63           Kiawairia Primary      Githunguri_1
64            Kibichoi Primary  Ruiru_Githunguri
65            Gitiha Secondary      Githunguri_1
66              Kigumo Primary             Other
67            Kigumo Secondary  Ruiru_Githunguri
68              Thuita Primary  Ruiru_Githunguri
69          Kiawaiguru Primary      Githunguri_1
70            Thuita Secondary  Ruiru_Githunguri
71            Mitahato Primary      Githunguri_2
72           Ndireti Secondary      Githunguri_2
73          Mitahato Secondary      Githunguri_2
74             Mukua Secondary      Githunguri_2

In [61]:
df["School"]

0              Ak Magugu Primary
1              Kamondo Secondary
2                Kamondo Primary
3                Karia Secondary
4                  Lioki Primary
5                 Ngemwa Primary
6              Kiairia Secondary
7               Ngemwa Secondary
8                Kiairia Primary
9             Githunguri Primary
10                 Karia Primary
11               Lioki Secondary
12            Gathanji Secondary
13              Gathanji Primary
14            Kahunira Secondary
15                 Ciiko Primary
16              Kahunira Primary
17               Kiababu Primary
18     Githunguri Tech Secondary
19                Gatitu Primary
20               Gathugu Primary
21           Pcea Kagema Primary
22            Gathangari Primary
23      William Ng'Iru Secondary
24               Githiga Primary
25                Gataka Primary
26    Gikang'A Kageche Secondary
27          Kiambururu Secondary
28               Kanyore Primary
29            Matuguta Secondary
30                 Ikinu Primary
31               Gitombo Primary
32              Mathanja Priamry
33                Gatina Primary
34                 Miiri Primary
35             Gathaithi Primary
36           Gathaithi Secondary
37               Ndireti Primary
38            Kiambururu Primary
39                 Ihiga Primary
40              Kanjai Secondary
41                Kambui Primary
42              Githioro Primary
43              Mukuyu Secondary
44              Miguta Secondary
45           Kiawairia Secondary
46               Githima Primary
47               Miiri Secondary
48                 Njunu Primary
49              Kagema Secondary
50             Gathugu Secondary
51             Giathieko Primary
52             Kihuririo Primary
53                 Nyaga Primary
54               Nyaga Secondary
55            Gathiruini Primary
56                 Ngewa Primary
57               Kindiga Primary
58                Miguta Primary
59              Komothai Primary
60              Matuguta Primary
61                Kanjai Primary
62               Riamute Primary
63             Kiawairia Primary
64              Kibichoi Primary
65              Gitiha Secondary
66                Kigumo Primary
67              Kigumo Secondary
68                Thuita Primary
69            Kiawaiguru Primary
70              Thuita Secondary
71              Mitahato Primary
72             Ndireti Secondary
73            Mitahato Secondary
74               Mukua Secondary
Name: School, dtype: object

In [54]:
#new column for month 
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month
df["Month"] = df["Date"].dt.month_name()

cols = list(df.columns)
cols.insert(3, cols.pop(cols.index("Month")))
df = df[cols]

In [55]:
def get_rice_variant(menu_item):
    if pd.isna(menu_item):
        return ""
    menu_item = menu_item.lower()
    if "masala" in menu_item:
        return "Masala"
    elif "tumeric" in menu_item:
        return "Tumeric"
    else:
        return "White"

df["Rice_variant"] = df["Menu"].apply(get_rice_variant)
# For column reordering to be next to menu 
cols = list(df.columns)
cols.insert(5, cols.pop(cols.index("Rice_variant")))
df = df[cols]

In [56]:
def clean_menu(name):
    if pd.isna(name):
        return None
    
    # Normalize casing and whitespace
    name = name.strip().title()
    
    # Replace connectors
    name = name.replace("&", "And")
    
    # Standardize synonyms/abbreviations
    name = re.sub(r"\bGg\b", "Greengrams", name, flags=re.IGNORECASE)
    name = name.replace("Green Gram", "Greengrams")
    name = name.replace("Green Grams", "Greengrams")
    
    # If "Rice" exists, discard everything before it
    if "Rice" in name:
        idx = name.find("Rice")
        name = name[idx:]
    
    # Canonical mapping
    if "Greengrams" in name:
        return "Rice and Greengrams"
    elif "Beans" in name:
        return "Rice and Beans"
    elif "Western" in name:
        return "Rice and Western"
    
    # If no keyword matched, return substring after Rice
    return name

In [57]:
df["Menu"] = df["Menu"].apply(clean_menu)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Kitchen                       75 non-null     object
 1   School                        75 non-null     object
 2   School_Type                   75 non-null     object
 3   Month                         75 non-null     object
 4   Date                          75 non-null     datetime64[ns]
 5   Rice_variant                  75 non-null     object
 6   Menu                          75 non-null     object
 7   Projected_Kids                75 non-null     int64
 8   Actual_Meals_Served           75 non-null     int64
 9   Successful_Taps               75 non-null     int64
 10  F4E_Supported_Kids            75 non-null     int64
 11  Teachers                      75 non-null     int64
 12  Staff_Meals                   75 non-null     int64
 13  Failed_Taps                   75 non-null     int64
 14  New_Registrations             75 non-null     int64
 15  New_Tags_Replaced             75 non-null     int64
 16  Rice_Remaining                74 non-null     float64
 17  B_W_G_Remaining               75 non-null     float64
 18  Missed_Food                   20 non-null     float64
 19  Next_Day_Projection_Students  75 non-null     int64
 20  Next_Day_Projection_Teachers  75 non-null     int64
 21  Next_Day_Projection_Staff     20 non-null     float64
 22  Start_Taping                  75 non-null     object
 23  Stop_Taping                   75 non-null     object
 24  Projection_Comment            20 non-null     object
 25  Comment_1                     75 non-null     object
 26  Comment_2                     74 non-null     object
 27  Comment_3                     74 non-null     object
 28  Comment_4                     74 non-null     object
 29  Reported_By                   75 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(11), object(14)
memory usage: 17.7+ KB

In [50]:
df[["Date","School","School_Type","Menu","Rice_variant","Kitchen"]].nunique()

Date             2
School          75
School_Type      2
Menu             2
Rice_variant     1
Kitchen          2
dtype: int64

In [51]:
df['Menu'].unique()

array(['Rice and Beans', 'Food Was Enough'], dtype=object)

In [41]:
# Convert to datetime
df["Start_Taping"] = pd.to_datetime(df["Start_Taping"], format="%d %b %Y, %H:%M:%S")
df["Stop_Taping"] = pd.to_datetime(df["Stop_Taping"], format="%d %b %Y, %H:%M:%S")
# Compute duration
lunch_time= df["Stop_Taping"] - df["Start_Taping"]
df["Lunch_Time_Min"] = (lunch_time.dt.total_seconds() / 60).round(0).astype('Int64')  # Convert to minutes and round


cols = list(df.columns)
# moving Lunch_Time_Min to index 23 nest to the parent columns
cols.insert(23, cols.pop(cols.index("Lunch_Time_Min")))

# Reassign DataFrame with new order
df = df[cols]

In [59]:

pd.set_option("display.max_rows", None)
df.head(3)

,Kitchen,School,School_Type,Month,Date,Rice_variant,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,kiambu kitchen,Ak Magugu Primary,Primary,February,2026-02-04,White,Rice and Western,430,415,375,...,0,3.0,"4 Feb 2026, 12:25:50","4 Feb 2026, 13:25:55",Normal school day,The food was delicious,The queue was orderly,The number of failed taps reduced from 16 to 1...,The number of successful taps reduced from 406...,@SC Margaret Maigua - Ak magugu comprehensive
1,kiambu kitchen,Kamondo Secondary,Secondary,February,2026-02-04,White,Rice and Western,135,123,123,...,0,2.0,"4 Feb 2026, 13:30:52","4 Feb 2026, 14:00:57",Expecting high turn up also the insufficient a...,Food was well cooked,Queue management was well managed with the hel...,Decrease from 6 to 4 as accounts were recharged,Slight decrease from 124 to 123 as some accoun...,"@Esther, Tapper kamondo secondary school"
2,kiambu kitchen,Kamondo Primary,Primary,February,2026-02-04,White,Rice and Western,350,364,327,...,0,3.0,"4 Feb 2026, 12:40:33","4 Feb 2026, 13:30:44",We expect turn up to decrease slightly,The food was well cooked and kids enjoyed the ...,The queue was well managed by the ToD,13 Failed taps a rise from 07 as respective pa...,327 Successful Taps a rise from 307 as turn up...,@SCwangengi -Kamondo primary school

In [ ]:
df.head(10)

In [ ]:
df.nunique()

In [43]:
#lets use os 
output_dir = r"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed"
base = date.replace(".csv", "")
output_path = os.path.join(output_dir, f"{base}_clean.csv")
df.to_csv(output_path, index=False)
print("Saved:", output_path)

Saved: C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed\03_02_26_clean.csv