In [1262]:
import pandas as pd
import numpy as np
import re
import os

In [ ]:
date="feb_2_26.csv"
df=pd.read_csv(fr"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_raw\extarcted_csv\{date}")
print(df.shape)

(101, 27)

In [1264]:
df.head()

,Kitchen,School,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,Staff_Meals,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,NaN,Kagema Primary School,2026-02-20,Rice and Green Grams,730,725,725,0.0,0,3,...,0,3,"20 Feb 2026, 12:50:31","20 Feb 2026, 13:35:41",NaN,Lunch was good and delicious,Queue management was smooth transitioning well...,Failed taps increased from 9 to 18 as more kid...,Successful taps increased from 719 to 725 succ...,@SL PCEA Kagema Comprehensive school
1,NaN,Mitahato Primary School,2026-02-20,White rice and green grams,250,243,215,20.0,0,2,...,0,2,"20 Feb 2026, 12:25:53","20 Feb 2026, 13:25:57",NaN,Food was delicious,Queue was transitioning from class to class,Today's failed taps were 6 because parents for...,Successful taps decreased from 251 to 243 this...,@SC George-Mitahato Comprehensive
2,NaN,Giathieko Primary School,2026-02-20,White rice and green grams.,200,192,175,17.0,0,2,...,0,2,"20 Feb 2026, 13:00:51","20 Feb 2026, 13:20:58",NaN,Food was delicious,Line was smooth .,"From 3 failed taps 10today , an increase noted...","From 199 to 192 today , a decrease recorded as...","@SC, Giathieko Comprehensive -Rose"
3,NaN,Nyaga Primary School,2026-02-20,Rice and Greengrams,520,521,457,64.0,0,3,...,0,3,"20 Feb 2026, 12:40:53","20 Feb 2026, 13:30:58",NaN,The food was delicious,The line was well managed by the school lead,The number of failed taps reduced from 29 to 1...,The number of actual meals served increased fr...,@SL Nyaga Primary and Junior School-Gladys
4,NaN,Githioro Primary School,2026-02-20,Rice and GREENGRAMS,345,338,312,26.0,0,2,...,0,2,"20 Feb 2026, 12:33:53","20 Feb 2026, 13:35:00",NaN,The food was appetising,Line management was organised assisted by tod,Failed taps increased from yesterday 5 to 8 to...,Successful taps decreased from yesterday’s 342...,@GITHIORO COMPREHENSIVE

In [1265]:
df.isnull().sum()

Kitchen                         101
School                            0
Date                              4
Menu                              4
Projected_Kids                    0
Actual_Meals_Served               0
Successful_Taps                   0
F4E_Supported_Kids                4
Teachers                          0
Staff_Meals                       0
Failed_Taps                       0
New_Registrations                 0
New_Tags_Replaced                 0
Rice_Remaining                    1
B_W_G_Remaining                   0
Missed_Food                      59
Next_Day_Projection_Students      0
Next_Day_Projection_Teachers      0
Next_Day_Projection_Staff         0
Start_Taping                      0
Stop_Taping                       0
Projection_Comment               55
Comment_1                         0
Comment_2                         0
Comment_3                         0
Comment_4                         0
Reported_By                       0
dtype: int64

In [1266]:
#stem and map the school names
df["School"]

0                                  Kagema Primary School
1                                Mitahato Primary School
2                               Giathieko Primary School
3                                   Nyaga Primary School
4                                Githioro Primary School
5              Kindiga Primary & Junior Secondary School
6                               Ndireti Secondary School
7                               Kihuririo Primary School
8                                  Miguta Primary School
9                               Gathugu Secondary School
10                               Gitiha Secondary School
11                               Kigumo Secondary School
12                                     Kiawairia Primary
13                               Mukuyu Secondary School
14                        PCEA Matuguta Secondary School
15                           Kiambururu Secondary School
16                             Gathangari Primary School
17                               Kibichoi Primary School
18                                Miiri Secondary School
19                               Miguta Secondary School
20                                Kanyore Primary School
21                                         Miiri Primary
22                            Gathaithi Secondary School
23                       William Ng'iru Secondary School
24                                         Ihiga Primary
25                                 Kambui Primary School
26                                Ndireti Primary School
27                                        Gatitu Primary
28                               Thuita Secondary School
29     Ceb Riamute Nursery, Primary & Junior Secondar...
30                               Kanjai Secondary School
31       PCEA Matuguta Primary & Junior Secondary School
32                                        Kigumo Primary
33                                Gitombo Primary School
34                                         Ikinu Primary
35                        PCEA Mitahato Secondary School
36                               Kagema Secondary School
37                                       Githiga Primary
38                                       Githima Primary
39                                     GATHAITHI PRIMARY
40                                 Thuita Primary School
41                                  Njunu Primary School
42                                        Kanjai Primary
43                                Nyaga Secondary School
44                            Kiawairia Secondary School
45                                  Ngewa Primary School
46                       Kiambururu Comprehensive School
47                                Gathugu Primary School
48                               Komothai Primary School
49                             Gathiruini Primary School
50     Catholic Archdiocese Of Nairobi Gataka Primary...
51                             Kiawaiguru Primary School
52                               Mathanja Priamry School
53                                 Gatina Primary School
54                     Gikang'a Kageche Secondary School
55                          Kibathi Comprehensive School
56                                Kiababu Primary School
57                    Njenga Karume Comprehensive School
58                          St. Augustine Gatono Primary
59                  St. Joseph Gathanga Secondary School
60                               Cianda Secondary School
61                              Kawaida Secondary School
62                         Gathanji Comprehensive School
63                          Kiairia Comprehensive School
64                    St. Vincent Lioki Secondary School
65                                Riara Secondary School
66                                      Ndumberi Primary
67                       P.C.E.A Ngemwa Secondary School
68                        P.C.E.A Karia Secondary School
69                     Kamondo Primary and Junior School
70                             ACK Riabai Primary School
71                          Kiambaa Comprehensive School
72                            Benson Njau Primary School
73                                         Ciiko Primary
74                       Mungai Chengecha Primary School
75                  PCEA Githunguri Comprehensive School
76                    St. Joseph Riabai Secondary School
77                                 Gicoco Primary School
78                            Lioki Comprehensive School
79                                 Maciri Primary School
80                             Gathanji Secondary School
81                                  Riara Primary School
82                  St. Peters Ndumberi Secondary School
83                       PCEA Karia Comprehensive School
84                                Mukua Secondary School
85                              Kiairia Secondary School
86                        AK Magugu Comprehensive School
87                              Ting'ang'a Model  School
88                           Ting'ang'a Secondary School
89                              Kamondo Secondary School
90                                 Loreto Primary School
91                             Kahunira Secondary School
92                       HGM Ting'ang'a Secondary School
93                         Kahunira Comprehensive School
94                          Gatatha Comprehensive School
95                      Ngemwa Primary and Junior School
96                         HGM Ting'ang'a Primary School
97                           Chief Wandie Primary School
98                          Kawaida Comprehensive School
99                               Kibubuti Primary School
100              Githunguri Technical & Secondary School
Name: School, dtype: object

In [1267]:
def clean_school_name(name):
    # Fixing  this typos for mathanja 
    name = name.replace("Primry", "Primary")
    
    # Replacing "Comprehensive" with "Primary"
    name = name.replace("Comprehensive", "Primary")
    
    # chopping the word "School" 
    name = re.sub(r"\b[Ss]chool\b", "", name)
    
    # remaoving  Junior Secondary" or similar suffixes
    name = re.sub(r"& Junior Secondary", "", name, flags=re.IGNORECASE)
    
    
    # Simplifying Catholic Archdiocese   and pcea
    if "Gataka" in name:
        return "Gataka Primary"
    if "Mitahato" in name:
        if "Secondary" in name:
            return "Mitahato Secondary"
        else:
            return "Mitahato Primary"
    if "Matuguta" in name:
        if "Secondary" in name:
            return "Matuguta Secondary"
        else:
            return "Matuguta Primary"
    if "Riamute" in name:
        return "Riamute Primary"
    if "Ngemwa" in name:
        if "Secondary" in name:
            return "Ngemwa Secondary"
        else:
            return "Ngemwa Primary"
    if "Lioki" in name:
        if "Secondary" in name:
            return "Lioki Secondary"
        else:
            return "Lioki Primary"
    if "Karia" in name:
        if "Secondary" in name:
            return "Karia Secondary"
        else:
            return "Karia Primary"
    if "Kamondo" in name:
        if "Secondary" in name:
            return "Kamondo Secondary"
        else:
            return "Kamondo Primary"
    if "Githunguri" in name:
        if "Secondary" in name:
            return "Githunguri Tech Secondary"
        else:
            return "Githunguri Primary"
    if "Mathanja" in name:
        return "Mathanja Primary"
    if "Kagema" in name:
        if "Secondary" in name:
            return "Kagema Secondary"
        else:
            return "Kagema Primary"
    
    
    
    #    spacing and capitalization
    name = " ".join(name.split())  # remove extra spaces
    name = name.title()            # standardize case
    
    return name.strip()

In [1268]:
df["School"] = df["School"].apply(clean_school_name)

In [1269]:
pd.describe_option("display.max_rows")
pd.set_option("display.max_rows", 100)

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: None]

In [1270]:
df['School']

0                 Kagema Primary
1               Mitahato Primary
2              Giathieko Primary
3                  Nyaga Primary
4               Githioro Primary
                 ...
96        Hgm Ting'Ang'A Primary
97          Chief Wandie Primary
98               Kawaida Primary
99              Kibubuti Primary
100    Githunguri Tech Secondary
Name: School, Length: 101, dtype: object

In [ ]:
#Going to moth of feb "Mukua Secondary" shift to kiambu kitchen   then we have a new school kagema primary serving from githunguri kitchen
githunguri_kitchen_schools= [
    "Kigumo Secondary",
    "Kigumo Primary",
    "Mukuyu Secondary",
    "Ihiga Primary",
    "Gathaithi Primary",
    "Githioro Primary",
    "Kindiga Primary",
    "Gitiha Secondary",
    "Gatitu Primary",
    "Kanyore Primary",
    "Matuguta Primary",
    "Mathanja Primary",
    "Gathaithi Secondary",
    "Gikang'A Kageche Secondary",
    "Matuguta Secondary",
    "Kiambururu Secondary",
    "Githiga Primary",
    "Gathangari Primary",
    "Gathiruini Primary",
    "Kiambururu Primary",
    "Thuita Secondary",
    "Kibichoi Primary",
    "Gatina Primary",
    "Gitombo Primary",
    "Kihuririo Primary",
    "Miiri Secondary",
    "Kiawaiguru Primary",
    "Kambui Primary",
    "Miguta Secondary",
    "Miguta Primary",
    "Ngewa Primary",
    "Mitahato Primary",
    "Gathugu Secondary",
    "Ndireti Secondary",
    "Giathieko Primary",
    "Ikinu Primary",
    "Kanjai Primary",
    "Mitahato Secondary",
    "Nyaga Primary",
    "Nyaga Secondary",
    "Riamute Primary",
    "Gathugu Primary",
    "Komothai Primary",
    "Kagema Secondary",
    "Kagema Primary",
    "Thuita Primary",
    "Miiri Primary",
    "Githima Primary",
    "William Ng'Iru Secondary",
    "Njunu Primary",
    "Kanjai Secondary",
    "Ndireti Primary",
    "Gataka Primary",
    "Kiawairia Primary",
    "Kiawairia Secondary"
]

kiambu_kitchen_schools = [
    "Karia Secondary",
    "Riara Primary",
    "Mukua Secondary",
    "Gathanji Secondary",
    "Ngemwa Primary",
    "Ting'Ang'A Secondary",
    "Cianda Secondary",
    "Lioki Primary",
    "Ndumberi Primary",
    "St. Joseph Riabai Secondary",
    "Mungai Chengecha Primary",
    "Maciri Primary",
    "Kiairia Secondary",
    "Gicoco Primary",
    "St. Peters Ndumberi Secondary",
    "Ack Riabai Primary",
    "Ting'Ang'A Model",
    "Lioki Secondary",
    "Kawaida Secondary",
    "Githunguri Tech Secondary",
    "Loreto Primary",
    "Kiababu Primary",
    "Benson Njau Primary",
    "Kibubuti Primary",
    "Hgm Ting'Ang'A Secondary",
    "Kawaida Primary",
    "Hgm Ting'Ang'A Primary",
    "Riara Secondary",
    "Karia Primary",
    "Chief Wandie Primary",
    "Ak Magugu Primary",
    "Kamondo Primary",
    "Kiairia Primary",
    "Ngemwa Secondary",
    "Githunguri Primary",
    "Kamondo Secondary",
    "Gatatha Primary",
    "Ciiko Primary",
    "Kahunira Secondary",
    "Kahunira Primary",
    "St. Augustine Gatono Primary",
    "Njenga Karume Primary",
    "Muongoiya Secondary",
    "Muchatha Secondary",
    "St. Joseph Gathanga Secondary",
    "Kiambaa Primary",
    "Gathanji Primary",
    "Mayuyu Primary",
    "Muchatha Primary",
    "Karuri Primary",
    "Kibathi Primary",
    "Muongoiya Primary"
]

In [1272]:

# creating a new columns of  the kichen served for each school 

#kiambu_kitchen_schools=["Githunguri Tech Secondary","Ngemwa Primary","Mukua Secondary","Ngemwa Secondary","Gathanji Primary","Gathanji Secondary","Lioki Primary","Kahunira Primary","Ak Magugu Primary","Lioki Secondary","Githunguri Primary","Karia Secondary","Karia Primary", "Ciiko Primary","Kiairia Secondary", "Kiairia Primary","Kahunira Secondary","Kamondo Secondary","Kamondo Primary", "Kiababu Primary"]
def map_kitchen_served(school_name):
    if school_name in kiambu_kitchen_schools:
        return 'Kiambu kitchen'
    elif school_name in githunguri_kitchen_schools:
        return 'Githunguri kitchen'
    else:
        return 'No kitchen found'
df["Kitchen"] = df["School"].apply(map_kitchen_served)

In [1273]:
df[["School","Kitchen"]]

                        School             Kitchen
0               Kagema Primary    No kitchen found
1             Mitahato Primary  Githunguri kitchen
2            Giathieko Primary  Githunguri kitchen
3                Nyaga Primary  Githunguri kitchen
4             Githioro Primary  Githunguri kitchen
..                         ...                 ...
96      Hgm Ting'Ang'A Primary      Kiambu kitchen
97        Chief Wandie Primary      Kiambu kitchen
98             Kawaida Primary      Kiambu kitchen
99            Kibubuti Primary      Kiambu kitchen
100  Githunguri Tech Secondary      Kiambu kitchen

[101 rows x 2 columns]

In [1274]:
df.groupby("Kitchen")["School"].count()

Kitchen
Githunguri kitchen    55
Kiambu kitchen        45
No kitchen found       1
Name: School, dtype: int64

In [1275]:
df[df["Kitchen"] == "No kitchen found"]

,Kitchen,School,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,Staff_Meals,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,No kitchen found,Kagema Primary,2026-02-20,Rice and Green Grams,730,725,725,0.0,0,3,...,0,3,"20 Feb 2026, 12:50:31","20 Feb 2026, 13:35:41",NaN,Lunch was good and delicious,Queue management was smooth transitioning well...,Failed taps increased from 9 to 18 as more kid...,Successful taps increased from 719 to 725 succ...,@SL PCEA Kagema Comprehensive school

In [1276]:
#schools type 
def get_school_type(name):
    name = name.lower()
    if "secondary" in name:
        return "Secondary"
    else:
        return "Primary"

df["School_Type"] = df["School"].apply(get_school_type)

#for good visual  i rearrabge the columns so school type can be be next to school name
cols = list(df.columns)
cols.insert(2, cols.pop(cols.index("School_Type")))
df = df[cols]

In [1277]:
df.head(5)

,Kitchen,School,School_Type,Date,Menu,Projected_Kids,Actual_Meals_Served,Successful_Taps,F4E_Supported_Kids,Teachers,...,Next_Day_Projection_Teachers,Next_Day_Projection_Staff,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,No kitchen found,Kagema Primary,Primary,2026-02-20,Rice and Green Grams,730,725,725,0.0,0,...,0,3,"20 Feb 2026, 12:50:31","20 Feb 2026, 13:35:41",NaN,Lunch was good and delicious,Queue management was smooth transitioning well...,Failed taps increased from 9 to 18 as more kid...,Successful taps increased from 719 to 725 succ...,@SL PCEA Kagema Comprehensive school
1,Githunguri kitchen,Mitahato Primary,Primary,2026-02-20,White rice and green grams,250,243,215,20.0,0,...,0,2,"20 Feb 2026, 12:25:53","20 Feb 2026, 13:25:57",NaN,Food was delicious,Queue was transitioning from class to class,Today's failed taps were 6 because parents for...,Successful taps decreased from 251 to 243 this...,@SC George-Mitahato Comprehensive
2,Githunguri kitchen,Giathieko Primary,Primary,2026-02-20,White rice and green grams.,200,192,175,17.0,0,...,0,2,"20 Feb 2026, 13:00:51","20 Feb 2026, 13:20:58",NaN,Food was delicious,Line was smooth .,"From 3 failed taps 10today , an increase noted...","From 199 to 192 today , a decrease recorded as...","@SC, Giathieko Comprehensive -Rose"
3,Githunguri kitchen,Nyaga Primary,Primary,2026-02-20,Rice and Greengrams,520,521,457,64.0,0,...,0,3,"20 Feb 2026, 12:40:53","20 Feb 2026, 13:30:58",NaN,The food was delicious,The line was well managed by the school lead,The number of failed taps reduced from 29 to 1...,The number of actual meals served increased fr...,@SL Nyaga Primary and Junior School-Gladys
4,Githunguri kitchen,Githioro Primary,Primary,2026-02-20,Rice and GREENGRAMS,345,338,312,26.0,0,...,0,2,"20 Feb 2026, 12:33:53","20 Feb 2026, 13:35:00",NaN,The food was appetising,Line management was organised assisted by tod,Failed taps increased from yesterday 5 to 8 to...,Successful taps decreased from yesterday’s 342...,@GITHIORO COMPREHENSIVE

In [1278]:
#region columns
Githunguri_1=["Kahunira Secondary","Ciiko Primary","Mukuyu Secondary","Kiawaiguru Primary","Gitiha Secondary","Kiawairia Primary","Matuguta Primary","Kindiga Primary","Gathiruini Primary","Kahunira Primary","Njunu Primary","Miiri Secondary","Githima Primary","Kiawairia Secondary","Miguta Secondary","Githioro Primary","Ihiga Primary","Kiambururu Primary","Gathaithi Secondary","Gathaithi Primary","Gatina Primary","Mathanja Primary","Gitombo Primary","Matuguta Secondary","Kanyore Primary","Kiambururu Secondary","Gikang'A Kageche Secondary","Gataka Primary","Githiga Primary","Kiababu Primary","Githunguri Tech Secondary","Gatitu Primary",]
Githunguri_2=["Karia Secondary","William Ng'Iru Secondary","Mukua Secondary","Mitahato Secondary","Ndireti Secondary","Mitahato Primary","Riamute Primary","Kanjai Primary","Komothai Primary","Miguta Primary","Ngewa Primary","Nyaga Secondary","Nyaga Primary","Giathieko Primary","Kambui Primary","Kanjai Secondary","Ndireti Primary","Miiri Primary","Ikinu Primary","Ak Magugu Primary","Kamondo Secondary","Kamondo Primary","","Lioki Primary","Gathangari Primary","Ngemwa Primary","Kiairia Secondary","Kiairia Primary","Githunguri Primary","Karia Primary","Lioki Secondary","Gathanji Secondary","Gathanji Primary","Ngemwa Secondary"]
Ruiru_Githunguri=["Gathugu Primary","Thuita Secondary","Kibichoi Primary","Gathugu Secondary","Kagema Secondary","Thuita Primary","Kigumo Secondary","Kigumo Primary","Kihuririo Primary","Kagema Primary"]
#new column for cluster 
def assign_cluster(school):
    if school in Githunguri_1:
        return "Githunguri 1"
    elif school in Githunguri_2:
        return "Githunguri 2"
    elif school in Ruiru_Githunguri:
        return "Ruiru-Githunguri"
    else:
        return "Kiambu Regions"

# Apply the function to the School column
df["Cluster"] = df["School"].apply(assign_cluster)

#for good visual  i re-arrange the columns so school type can be be next to school name
cols = list(df.columns)
cols.insert(2, cols.pop(cols.index("Cluster")))# outdo the previous setup of school type in the upper part of the code
df = df[cols]

In [1293]:
df[["School", "Cluster"]]

                            School           Cluster
0                   Kagema Primary  Ruiru-Githunguri
1                 Mitahato Primary      Githunguri 2
2                Giathieko Primary      Githunguri 2
3                    Nyaga Primary      Githunguri 2
4                 Githioro Primary      Githunguri 1
5                  Kindiga Primary      Githunguri 1
6                Ndireti Secondary      Githunguri 2
7                Kihuririo Primary  Ruiru-Githunguri
8                   Miguta Primary      Githunguri 2
9                Gathugu Secondary  Ruiru-Githunguri
10                Gitiha Secondary      Githunguri 1
11                Kigumo Secondary  Ruiru-Githunguri
12               Kiawairia Primary      Githunguri 1
13                Mukuyu Secondary      Githunguri 1
14              Matuguta Secondary      Githunguri 1
15            Kiambururu Secondary      Githunguri 1
16              Gathangari Primary      Githunguri 2
17                Kibichoi Primary  Ruiru-Githunguri
18                 Miiri Secondary      Githunguri 1
19                Miguta Secondary      Githunguri 1
20                 Kanyore Primary      Githunguri 1
21                   Miiri Primary      Githunguri 2
22             Gathaithi Secondary      Githunguri 1
23        William Ng'Iru Secondary      Githunguri 2
24                   Ihiga Primary      Githunguri 1
25                  Kambui Primary      Githunguri 2
26                 Ndireti Primary      Githunguri 2
27                  Gatitu Primary      Githunguri 1
28                Thuita Secondary  Ruiru-Githunguri
29                 Riamute Primary      Githunguri 2
30                Kanjai Secondary      Githunguri 2
31                Matuguta Primary      Githunguri 1
32                  Kigumo Primary  Ruiru-Githunguri
33                 Gitombo Primary      Githunguri 1
34                   Ikinu Primary      Githunguri 2
35              Mitahato Secondary      Githunguri 2
36                Kagema Secondary  Ruiru-Githunguri
37                 Githiga Primary      Githunguri 1
38                 Githima Primary      Githunguri 1
39               Gathaithi Primary      Githunguri 1
40                  Thuita Primary  Ruiru-Githunguri
41                   Njunu Primary      Githunguri 1
42                  Kanjai Primary      Githunguri 2
43                 Nyaga Secondary      Githunguri 2
44             Kiawairia Secondary      Githunguri 1
45                   Ngewa Primary      Githunguri 2
46              Kiambururu Primary      Githunguri 1
47                 Gathugu Primary  Ruiru-Githunguri
48                Komothai Primary      Githunguri 2
49              Gathiruini Primary      Githunguri 1
50                  Gataka Primary      Githunguri 1
51              Kiawaiguru Primary      Githunguri 1
52                Mathanja Primary      Githunguri 1
53                  Gatina Primary      Githunguri 1
54      Gikang'A Kageche Secondary      Githunguri 1
55                 Kibathi Primary    Kiambu Regions
56                 Kiababu Primary      Githunguri 1
57           Njenga Karume Primary    Kiambu Regions
58    St. Augustine Gatono Primary    Kiambu Regions
59   St. Joseph Gathanga Secondary    Kiambu Regions
60                Cianda Secondary    Kiambu Regions
61               Kawaida Secondary    Kiambu Regions
62                Gathanji Primary      Githunguri 2
63                 Kiairia Primary      Githunguri 2
64                 Lioki Secondary      Githunguri 2
65                 Riara Secondary    Kiambu Regions
66                Ndumberi Primary    Kiambu Regions
67                Ngemwa Secondary      Githunguri 2
68                 Karia Secondary      Githunguri 2
69                 Kamondo Primary      Githunguri 2
70              Ack Riabai Primary    Kiambu Regions
71                 Kiambaa Primary    Kiambu Regions
72             Benson Njau Primary    Kiambu Regions
73                   Ciiko Primary      Githunguri 1
74        Mungai Chengecha Primary    Kiambu Regions
75              Githunguri Primary      Githunguri 2
76     St. Joseph Riabai Secondary    Kiambu Regions
77                  Gicoco Primary    Kiambu Regions
78                   Lioki Primary      Githunguri 2
79                  Maciri Primary    Kiambu Regions
80              Gathanji Secondary      Githunguri 2
81                   Riara Primary    Kiambu Regions
82   St. Peters Ndumberi Secondary    Kiambu Regions
83                   Karia Primary      Githunguri 2
84                 Mukua Secondary      Githunguri 2
85               Kiairia Secondary      Githunguri 2
86               Ak Magugu Primary      Githunguri 2
87                Ting'Ang'A Model    Kiambu Regions
88            Ting'Ang'A Secondary    Kiambu Regions
89               Kamondo Secondary      Githunguri 2
90                  Loreto Primary    Kiambu Regions
91              Kahunira Secondary      Githunguri 1
92        Hgm Ting'Ang'A Secondary    Kiambu Regions
93                Kahunira Primary      Githunguri 1
94                 Gatatha Primary    Kiambu Regions
95                  Ngemwa Primary      Githunguri 2
96          Hgm Ting'Ang'A Primary    Kiambu Regions
97            Chief Wandie Primary    Kiambu Regions
98                 Kawaida Primary    Kiambu Regions
99                Kibubuti Primary    Kiambu Regions
100      Githunguri Tech Secondary      Githunguri 1

In [1280]:
df["School"]

0                 Kagema Primary
1               Mitahato Primary
2              Giathieko Primary
3                  Nyaga Primary
4               Githioro Primary
                 ...
96        Hgm Ting'Ang'A Primary
97          Chief Wandie Primary
98               Kawaida Primary
99              Kibubuti Primary
100    Githunguri Tech Secondary
Name: School, Length: 101, dtype: object

In [1281]:
#new column for month 
df["Date"] = pd.to_datetime(df["Date"], errors="coerce", format="mixed", dayfirst=True)
first_valid_date = df["Date"].dropna().iloc[0]
df["Date"] = df["Date"].fillna(first_valid_date)
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month
df["Month"] = df["Date"].dt.month_name()

cols = list(df.columns)
cols.insert(3, cols.pop(cols.index("Month")))
df = df[cols]

In [1282]:
def get_rice_variant(menu_item):
    if pd.isna(menu_item):
        return ""
    menu_item = menu_item.lower()
    if "masala" in menu_item:
        return "Masala"
    elif "tumeric" in menu_item:
        return "Tumeric"
    else:
        return "White"

df["Rice_variant"] = df["Menu"].apply(get_rice_variant)
# For column reordering to be next to menu 
cols = list(df.columns)
cols.insert(5, cols.pop(cols.index("Rice_variant")))
df = df[cols]

In [1283]:
def clean_menu(name):
    if pd.isna(name):
        return None
    
    # Normalize casing and whitespace
    name = name.strip().title()
    
    # Replace connectors
    name = name.replace("&", "And")
    
    # Standardize synonyms/abbreviations
    name = re.sub(r"\bGg\b", "Greengrams", name, flags=re.IGNORECASE)
    name = re.sub(r"\bG\.G\b", "Greengrams", name, flags=re.IGNORECASE)
    name = re.sub(r"Riceandgg", "Rice and Greengrams", name, flags=re.IGNORECASE)
    name = name.replace("Green Gram", "Greengrams")
    name = name.replace("Green Grams", "Greengrams")
    name = name.replace("Greengram", "Greengrams")
    
    # If "Rice" exists, discard everything before it
    if "Rice" in name:
        idx = name.find("Rice")
        name = name[idx:]
    
    # Canonical mapping
    if "Greengrams" in name:
        return "Rice and Greengrams"
    elif "Beans" in name:
        return "Rice and Beans"
    elif "Western" in name:
        return "Rice and Western"
    
    # If no keyword matched, return substring after Rice
    return name

In [1284]:
df["Menu"] = df["Menu"].apply(clean_menu)

In [1285]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Kitchen                       101 non-null    object
 1   School                        101 non-null    object
 2   Cluster                       101 non-null    object
 3   Month                         101 non-null    object
 4   School_Type                   101 non-null    object
 5   Rice_variant                  101 non-null    object
 6   Date                          101 non-null    datetime64[ns]
 7   Menu                          97 non-null     object
 8   Projected_Kids                101 non-null    int64
 9   Actual_Meals_Served           101 non-null    int64
 10  Successful_Taps               101 non-null    int64
 11  F4E_Supported_Kids            97 non-null     float64
 12  Teachers                      101 non-null    int64
 13  Staff_Meals                   101 non-null    int64
 14  Failed_Taps                   101 non-null    int64
 15  New_Registrations             101 non-null    int64
 16  New_Tags_Replaced             101 non-null    int64
 17  Rice_Remaining                100 non-null    float64
 18  B_W_G_Remaining               101 non-null    float64
 19  Missed_Food                   42 non-null     float64
 20  Next_Day_Projection_Students  101 non-null    int64
 21  Next_Day_Projection_Teachers  101 non-null    int64
 22  Next_Day_Projection_Staff     101 non-null    int64
 23  Start_Taping                  101 non-null    object
 24  Stop_Taping                   101 non-null    object
 25  Projection_Comment            46 non-null     object
 26  Comment_1                     101 non-null    object
 27  Comment_2                     101 non-null    object
 28  Comment_3                     101 non-null    object
 29  Comment_4                     101 non-null    object
 30  Reported_By                   101 non-null    object
dtypes: datetime64[ns](1), float64(4), int64(11), object(15)
memory usage: 24.6+ KB

In [1286]:
df[["Date","School","School_Type","Menu","Rice_variant","Kitchen"]].nunique()

Date              1
School          101
School_Type       2
Menu              6
Rice_variant      2
Kitchen           3
dtype: int64

In [1287]:
df['Menu'].value_counts()

Menu
Rice and Greengrams     52
Rice and Western        41
Food Was Delicious       1
Whiterice  And Green     1
Rice and Beans           1
Rice                     1
Name: count, dtype: int64

In [1288]:
# Convert to datetime

df["Start_Taping"] = pd.to_datetime(df["Start_Taping"], errors="coerce", format="mixed")
df["Stop_Taping"]  = pd.to_datetime(df["Stop_Taping"], errors="coerce", format="mixed")
df["Start_Taping"] = pd.to_datetime(df["Start_Taping"], format="%d %b %Y, %H:%M:%S")
df["Stop_Taping"] = pd.to_datetime(df["Stop_Taping"], format="%d %b %Y, %H:%M:%S")
# Compute duration
lunch_time= df["Stop_Taping"] - df["Start_Taping"]
df["Lunch_Time_Min"] = (lunch_time.dt.total_seconds() / 60).round(0).astype('Int64')  # Convert to minutes and round


cols = list(df.columns)
# moving Lunch_Time_Min to index 23 nest to the parent columns
cols.insert(23, cols.pop(cols.index("Lunch_Time_Min")))

# Reassign DataFrame with new order
df = df[cols]

In [1289]:

pd.set_option("display.max_rows", None)
df.head(3)

,Kitchen,School,Cluster,Month,School_Type,Rice_variant,Date,Menu,Projected_Kids,Actual_Meals_Served,...,Next_Day_Projection_Staff,Lunch_Time_Min,Start_Taping,Stop_Taping,Projection_Comment,Comment_1,Comment_2,Comment_3,Comment_4,Reported_By
0,No kitchen found,Kagema Primary,Ruiru-Githunguri,February,Primary,White,2026-02-20,Rice and Greengrams,730,725,...,3,45,2026-02-20 12:50:31,2026-02-20 13:35:41,NaN,Lunch was good and delicious,Queue management was smooth transitioning well...,Failed taps increased from 9 to 18 as more kid...,Successful taps increased from 719 to 725 succ...,@SL PCEA Kagema Comprehensive school
1,Githunguri kitchen,Mitahato Primary,Githunguri 2,February,Primary,White,2026-02-20,Rice and Greengrams,250,243,...,2,60,2026-02-20 12:25:53,2026-02-20 13:25:57,NaN,Food was delicious,Queue was transitioning from class to class,Today's failed taps were 6 because parents for...,Successful taps decreased from 251 to 243 this...,@SC George-Mitahato Comprehensive
2,Githunguri kitchen,Giathieko Primary,Githunguri 2,February,Primary,White,2026-02-20,Rice and Greengrams,200,192,...,2,20,2026-02-20 13:00:51,2026-02-20 13:20:58,NaN,Food was delicious,Line was smooth .,"From 3 failed taps 10today , an increase noted...","From 199 to 192 today , a decrease recorded as...","@SC, Giathieko Comprehensive -Rose"

In [1290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Kitchen                       101 non-null    object
 1   School                        101 non-null    object
 2   Cluster                       101 non-null    object
 3   Month                         101 non-null    object
 4   School_Type                   101 non-null    object
 5   Rice_variant                  101 non-null    object
 6   Date                          101 non-null    datetime64[ns]
 7   Menu                          97 non-null     object
 8   Projected_Kids                101 non-null    int64
 9   Actual_Meals_Served           101 non-null    int64
 10  Successful_Taps               101 non-null    int64
 11  F4E_Supported_Kids            97 non-null     float64
 12  Teachers                      101 non-null    int64
 13  Staff_Meals                   101 non-null    int64
 14  Failed_Taps                   101 non-null    int64
 15  New_Registrations             101 non-null    int64
 16  New_Tags_Replaced             101 non-null    int64
 17  Rice_Remaining                100 non-null    float64
 18  B_W_G_Remaining               101 non-null    float64
 19  Missed_Food                   42 non-null     float64
 20  Next_Day_Projection_Students  101 non-null    int64
 21  Next_Day_Projection_Teachers  101 non-null    int64
 22  Next_Day_Projection_Staff     101 non-null    int64
 23  Lunch_Time_Min                101 non-null    Int64
 24  Start_Taping                  101 non-null    datetime64[ns]
 25  Stop_Taping                   101 non-null    datetime64[ns]
 26  Projection_Comment            46 non-null     object
 27  Comment_1                     101 non-null    object
 28  Comment_2                     101 non-null    object
 29  Comment_3                     101 non-null    object
 30  Comment_4                     101 non-null    object
 31  Reported_By                   101 non-null    object
dtypes: Int64(1), datetime64[ns](3), float64(4), int64(11), object(13)
memory usage: 25.5+ KB

In [1291]:
df.nunique()

Kitchen                           3
School                          101
Cluster                           4
Month                             1
School_Type                       2
Rice_variant                      2
Date                              1
Menu                              6
Projected_Kids                   69
Actual_Meals_Served              92
Successful_Taps                  93
F4E_Supported_Kids               45
Teachers                          7
Staff_Meals                       6
Failed_Taps                      31
New_Registrations                 3
New_Tags_Replaced                 9
Rice_Remaining                   18
B_W_G_Remaining                  20
Missed_Food                       1
Next_Day_Projection_Students     67
Next_Day_Projection_Teachers      7
Next_Day_Projection_Staff         7
Lunch_Time_Min                   44
Start_Taping                     93
Stop_Taping                      89
Projection_Comment               46
Comment_1                        50
Comment_2                        88
Comment_3                       101
Comment_4                       101
Reported_By                     101
dtype: int64

In [1292]:
#lets use os 
output_dir = r"C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed"
base = date.replace(".csv", "")
output_path = os.path.join(output_dir, f"{base}_clean.csv")
df.to_csv(output_path, index=False)
print("Saved:", output_path)

Saved: C:\Users\Administrator\Desktop\ds\f4e\githunguri1\Githunguri-kitchen-f4e-dashboard\data\data_processed\feb_20_26_clean.csv